<div style="
    display:flex;
    justify-content:center;
    align-items:center;
    width:78%;
    margin:40px auto;
    border-radius:14px;
    background: linear-gradient(45deg, #8a2be2, #ff3cac, #2bd2ff, #8a2be2);
    background-size: 300% 300%;
    animation: borderFlow 7s linear infinite;
    padding:2px;
    box-sizing:border-box;
">
  <div style="
      display:flex;
      align-items:center;
      justify-content:center;
      flex-wrap:wrap;
      gap:22px;
      background: linear-gradient(90deg, rgba(18,18,28,0.96), rgba(28,18,40,0.96));
      color: white;
      font-family: 'Segoe UI', Arial, sans-serif;
      font-size: 25px;
      font-weight: 650;
      letter-spacing: 1px;
      padding: 20px 34px;
      border-radius: 12px;
      width: 100%;
      height: 100%;
      box-sizing:border-box;
  ">
    <img src="assets/img/logo.png"
         alt="Logo La poule qui chante"
         style="height:120px; width:auto; filter: drop-shadow(0 0 10px rgba(255,195,90,0.30));">
    <div style="text-align:center;">
      <div style="font-size:30px; font-weight:700; letter-spacing:1px;">
        La poule qui chante
      </div>
      <span style="font-size:22px; opacity:0.95;">
        Préparation, nettoyage et analyse exploratoire des données
      </span><br>
      <span style="font-size:16px; opacity:0.78; letter-spacing:0.4px;">
        International market screening for poultry export strategy
      </span>
    </div>
  </div>
</div>

<style>
@keyframes borderFlow {
  0% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
}
</style>

# 🎯 Objectif du projet • La poule qui chante 🐔

Ce notebook a pour objectif de **préparer, nettoyer et structurer un jeu de données international** permettant d’identifier des **groupes de pays à cibler pour l’exportation de poulets** par l’entreprise fictive **La poule qui chante**.

L’enjeu est de construire une base d’analyse fiable, exploitable et cohérente, à partir de données issues principalement de la **FAO**, enrichies si nécessaire par d’autres sources open data.

---

## 🧩 Contexte

La direction de **La poule qui chante** souhaite initier une stratégie d’**expansion à l’international**.  
Dans un premier temps, elle ne demande pas une étude de marché pays par pays, mais une **analyse macro** permettant de :

- comparer les pays sur des critères alimentaires, démographiques et économiques ;
- identifier des **groupes homogènes de pays** ;
- faire émerger des **priorités de ciblage** pour de futures analyses marché plus détaillées.

L’analyse devra ensuite être présentée au **COMEX** dans un format clair, synthétique et accessible à un public non technique.

---

## 📌 Objectifs de ce notebook

Ce premier notebook vise à :

- importer et comprendre les données FAO mises à disposition ;
- sélectionner des **variables pertinentes** pour la problématique d’exportation ;
- enrichir l’analyse par une réflexion **PESTEL** ;
- nettoyer, transformer et fusionner les données ;
- construire un **dataset final complet**, sans valeurs manquantes sur les pays retenus ;
- créer des **variables dérivées** utiles à la future segmentation ;
- réaliser une **analyse exploratoire** afin de mieux comprendre la structure des données avant l’ACP et le clustering.

---

## 🧠 Finalité

Ce notebook constitue le socle méthodologique du projet.  
Le dataset produit ici sera ensuite utilisé dans un second notebook dédié à :

- l’**ACP** ;
- la **réduction de dimension** ;
- la **segmentation des pays** via CAH et K-means ;
- la formulation de **recommandations stratégiques** à destination du COMEX.

<a id="top"></a>

<h2 style="color:RGB(170,90,255);">📘 Sommaire</h2>

<ul style="list-style:none; line-height:1.8; font-size:17px; padding-left:0;">

  <li>
    <a href="#etape1" style="color:RGB(170,90,255); text-decoration:none;">📂 Étape 1 • Importation et cadrage du projet</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape1_1" style="color:RGB(170,90,255); text-decoration:none;">1.1 Importation des librairies</a></li>
      <li><a href="#etape1_2" style="color:RGB(170,90,255); text-decoration:none;">1.2 Chargement des données FAO</a></li>
      <li><a href="#etape1_3" style="color:RGB(170,90,255); text-decoration:none;">1.3 Rappel de la problématique métier</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape2" style="color:RGB(120,210,255); text-decoration:none;">🌍 Étape 2 • Compréhension et sélection des variables</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape2_1" style="color:RGB(120,210,255); text-decoration:none;">2.1 Lecture de la structure des fichiers</a></li>
      <li><a href="#etape2_2" style="color:RGB(120,210,255); text-decoration:none;">2.2 Réflexion PESTEL appliquée au projet</a></li>
      <li><a href="#etape2_3" style="color:RGB(120,210,255); text-decoration:none;">2.3 Sélection des variables pertinentes</a></li>
      <li><a href="#etape2_4" style="color:RGB(120,210,255); text-decoration:none;">2.4 Justification métier des variables retenues</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape3" style="color:RGB(255,170,80); text-decoration:none;">🧹 Étape 3 • Préparation et nettoyage des données</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape3_1" style="color:RGB(255,170,80); text-decoration:none;">3.1 Pivot des données par pays</a></li>
      <li><a href="#etape3_2" style="color:RGB(255,170,80); text-decoration:none;">3.2 Filtrage des indicateurs utiles</a></li>
      <li><a href="#etape3_3" style="color:RGB(255,170,80); text-decoration:none;">3.3 Contrôle des types et unités</a></li>
      <li><a href="#etape3_4" style="color:RGB(255,170,80); text-decoration:none;">3.4 Exclusion des petits territoires atypiques</a></li>     
      <li><a href="#etape3_5" style="color:RGB(255,170,80); text-decoration:none;">3.5 Gestion des valeurs manquantes</a></li>
      <li><a href="#etape3_6" style="color:RGB(255,170,80); text-decoration:none;">3.6 Traitement des doublons</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape4" style="color:RGB(120,255,170); text-decoration:none;">🔗 Étape 4 • Construction du dataset d’analyse</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape4_1" style="color:RGB(120,255,170); text-decoration:none;">4.1 Intégration de la population</a></li>
      <li><a href="#etape4_2" style="color:RGB(120,255,170); text-decoration:none;">4.2 Ajout d’éventuelles sources externes</a></li>
      <li><a href="#etape4_3" style="color:RGB(120,255,170); text-decoration:none;">4.3 Création du dataset final enrichi</a></li>
      <li><a href="#etape4_4" style="color:RGB(120,255,170); text-decoration:none;">4.4 Vérification du périmètre final (100 pays minimum)</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape5" style="color:RGB(255,120,190); text-decoration:none;">🛠️ Étape 5 • Feature engineering</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape5_1" style="color:RGB(255,120,190); text-decoration:none;">5.1 Création des variables dérivées</a></li>
      <li><a href="#etape5_2" style="color:RGB(255,120,190); text-decoration:none;">5.2 Contrôle de cohérence des nouvelles variables</a></li>
      <li><a href="#etape5_3" style="color:RGB(255,120,190); text-decoration:none;">5.3 Dataset final prêt pour l’ACP</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape6" style="color:RGB(255,210,90); text-decoration:none;">🔎 Étape 6 • Analyse exploratoire des données</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape6_1" style="color:RGB(255,210,90); text-decoration:none;">6.1 Statistiques descriptives</a></li>
      <li><a href="#etape6_2" style="color:RGB(255,210,90); text-decoration:none;">6.2 Distribution des variables</a></li>
      <li><a href="#etape6_3" style="color:RGB(255,210,90); text-decoration:none;">6.3 Détection des outliers</a></li>
      <li><a href="#etape6_4" style="color:RGB(255,210,90); text-decoration:none;">6.4 Première lecture business des profils pays</a></li>
    </ul>
  </li>

  <li>
    <a href="#conclusion1" style="color:RGB(39,245,211); text-decoration:none;">Conclusion du notebook 1</a>
  </li>

</ul>

<a id="etape1"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(168,85,247,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(72,8,92,0.96), rgba(44,7,60,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(82%) sepia(18%) saturate(2017%) hue-rotate(271deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span style="color:#FFFFFF;">📂 Étape 1</span>
    <span>• Importation et cadrage du projet</span>
  </h2>
</div>

<a id="etape1_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(196,132,252,0.28);
  border-radius:12px;
  background:rgba(196,132,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(13%) saturate(1045%) hue-rotate(238deg) brightness(103%) contrast(103%);
      ">
    </a>
    <span>1.1 • Importation des librairies</span>
  </h3>
</div>

In [366]:
# Importation des librairies principales
from IPython.display import display, HTML

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

print("✅ Librairies importées avec succès.")

✅ Librairies importées avec succès.

In [367]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 120)

def format_large_number_fr(value, unit=""):
    if pd.isna(value):
        return "NA"

    abs_value = abs(value)

    if abs_value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f} milliards {unit}".strip()
    elif abs_value >= 1_000_000:
        return f"{value / 1_000_000:.2f} millions {unit}".strip()
    elif abs_value >= 1_000:
        return f"{value:,.0f} {unit}".replace(",", " ").strip()
    else:
        return f"{value:.2f} {unit}".strip()

def display_number_fr(x):
    if pd.isna(x):
        return "NA"

    abs_x = abs(x)

    if abs_x >= 1_000_000_000:
        return f"{x / 1_000_000_000:.2f} milliards"
    elif abs_x >= 1_000_000:
        return f"{x / 1_000_000:.2f} millions"
    elif abs_x >= 1_000:
        return f"{x:,.0f}".replace(",", " ")
    else:
        return f"{x:.2f}"

pd.options.display.float_format = display_number_fr

print("✅ Options d'affichage pandas configurées.")

✅ Options d'affichage pandas configurées.

<a id="etape1_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(196,132,252,0.28);
  border-radius:12px;
  background:rgba(196,132,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(13%) saturate(1045%) hue-rotate(238deg) brightness(103%) contrast(103%);
      ">
    </a>
    <span>1.2 • Chargement des données FAO</span>
  </h3>
</div>

In [368]:
# Chargement des fichiers CSV
dispo = pd.read_csv(
    "data/DisponibiliteAlimentaire_2017.csv",
    sep=","
)

print("✅ Fichiers chargés avec succès.")

# Chargement des fichiers CSV
population = pd.read_csv(
    "data/Population_2000_2018.csv",
    sep=","
)

print("✅ Fichiers chargés avec succès.")

✅ Fichiers chargés avec succès.
✅ Fichiers chargés avec succès.

In [369]:
# Dimensions des datasets
print("Dimensions du fichier Disponibilité alimentaire :", dispo.shape)
print("Dimensions du fichier Population :", population.shape)

Dimensions du fichier Disponibilité alimentaire : (176600, 14)
Dimensions du fichier Population : (4411, 15)

In [370]:
# Aperçu des premières lignes du fichier disponibilité alimentaire
dispo.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2511,Blé et produits,2017,2017,Milliers de tonnes,4 281,S,Données standardisées
1,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,2 302,S,Données standardisées
2,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2511,Blé et produits,2017,2017,Milliers de tonnes,-119.00,S,Données standardisées
3,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5911,Exportations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
4,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé et produits,2017,2017,Milliers de tonnes,6 701,S,Données standardisées

In [371]:
# Aperçu des premières lignes du fichier population

population.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2000,2000,1000 personnes,20 780,X,Sources internationales sûres,NaN
1,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2001,2001,1000 personnes,21 607,X,Sources internationales sûres,NaN
2,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2002,2002,1000 personnes,22 601,X,Sources internationales sûres,NaN
3,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2003,2003,1000 personnes,23 681,X,Sources internationales sûres,NaN
4,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2004,2004,1000 personnes,24 727,X,Sources internationales sûres,NaN

In [372]:
# Informations générales sur le fichier disponibilité alimentaire
dispo.info()

<class 'pandas.DataFrame'>
RangeIndex: 176600 entries, 0 to 176599
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Code Domaine            176600 non-null  str
 1   Domaine                 176600 non-null  str
 2   Code zone               176600 non-null  int64
 3   Zone                    176600 non-null  str
 4   Code Élément            176600 non-null  int64
 5   Élément                 176600 non-null  str
 6   Code Produit            176600 non-null  int64
 7   Produit                 176600 non-null  str
 8   Code année              176600 non-null  int64
 9   Année                   176600 non-null  int64
 10  Unité                   176600 non-null  str
 11  Valeur                  176600 non-null  float64
 12  Symbole                 176600 non-null  str
 13  Description du Symbole  176600 non-null  str
dtypes: float64(1), int64(5), str(8)
memory usage: 18.9 MB

In [373]:
# Informations générales sur le fichier population
population.info()

<class 'pandas.DataFrame'>
RangeIndex: 4411 entries, 0 to 4410
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            4411 non-null   str
 1   Domaine                 4411 non-null   str
 2   Code zone               4411 non-null   int64
 3   Zone                    4411 non-null   str
 4   Code Élément            4411 non-null   int64
 5   Élément                 4411 non-null   str
 6   Code Produit            4411 non-null   int64
 7   Produit                 4411 non-null   str
 8   Code année              4411 non-null   int64
 9   Année                   4411 non-null   int64
 10  Unité                   4411 non-null   str
 11  Valeur                  4411 non-null   float64
 12  Symbole                 4411 non-null   str
 13  Description du Symbole  4411 non-null   str
 14  Note                    258 non-null    str
dtypes: float64(1), int64(5), str(9)
memory usage: 517.0 KB

In [374]:
# Vérification des valeurs manquantes dans les fichiers sources
missing_dispo = dispo.isnull().sum().sort_values(ascending=False)
missing_population = population.isnull().sum().sort_values(ascending=False)

display(HTML("<h3 style='color:#C084FC;'>Valeurs manquantes — Disponibilité alimentaire</h3>"))
display(missing_dispo[missing_dispo > 0])

display(HTML("<h3 style='color:#C084FC;'>Valeurs manquantes — Population</h3>"))
display(missing_population[missing_population > 0])

Series([], dtype: int64)

Note    4153
dtype: int64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(31,14,54,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(196,132,252,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">📂</span>
    <b style="font-size:19px; color:#E9C7FF;">Étape 1.2 • Chargement des données FAO</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Deux fichiers sources ont été importés afin de construire la base de travail du projet :
    un fichier de <b style="color:#D8B4FE;">disponibilité alimentaire</b> et un fichier de
    <b style="color:#D8B4FE;">population</b>.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(168,85,247,0.08);
      border:1px solid rgba(168,85,247,0.28);
    ">
      <div style="font-weight:700; color:#E9C7FF; margin-bottom:6px;">🍗 Disponibilité alimentaire</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>176 600</b> lignes</li>
        <li><b>14</b> colonnes</li>
        <li>Données alimentaires par pays, produit et indicateur</li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🌍 Population</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>4 411</b> lignes</li>
        <li><b>15</b> colonnes</li>
        <li>Données de population par pays et par année</li>
      </ul>
    </div>

  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Contrôle du chargement :</b><br>
    Les deux fichiers ont été chargés correctement. Les premières lignes confirment que les données contiennent
    les colonnes attendues, notamment <b>Zone</b>, <b>Produit</b>, <b>Élément</b>, <b>Année</b>, <b>Unité</b> et <b>Valeur</b>.
  </div>

  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.30);
  ">
    🔎 <b style="color:#FDE68A;">Lecture initiale :</b><br>
    Le fichier de disponibilité alimentaire ne présente pas de valeurs manquantes visibles sur les colonnes utiles.
    Dans le fichier population, la colonne <b>Note</b> contient des valeurs manquantes, mais cette colonne est descriptive
    et ne sera pas utilisée pour l’analyse.
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Les fichiers sources sont exploitables pour démarrer l’étude. La prochaine étape consiste à comprendre leur structure,
    identifier les indicateurs disponibles et sélectionner les variables pertinentes pour une stratégie d’exportation de volaille.
  </div>

</div>

<a id="etape1_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(196,132,252,0.28);
  border-radius:12px;
  background:rgba(196,132,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(13%) saturate(1045%) hue-rotate(238deg) brightness(103%) contrast(103%);
      ">
    </a>
    <span>1.3 • Rappel de la problématique métier</span>
  </h3>
</div>

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(53,18,72,0.96), rgba(20,18,28,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(236,72,153,0.32);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:21px;">🐔</span>
    <b style="font-size:19px; color:#F9A8D4;">Étape 1.3 • Rappel de la problématique métier</b>
  </div>
  <p style="margin:0 0 12px 0;">
    L’entreprise fictive <b style="color:#FDE68A;">La poule qui chante</b> souhaite développer son activité
    à l’international. L’objectif n’est pas encore de réaliser une étude de marché détaillée pays par pays,
    mais d’identifier des <b style="color:#F9A8D4;">groupes de pays prometteurs</b> pour l’exportation de poulets.
  </p>

  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(236,72,153,0.08);
      border:1px solid rgba(236,72,153,0.28);
    ">
      <div style="font-weight:700; color:#F9A8D4; margin-bottom:6px;">🎯 Objectif business</div>
      <p style="margin:0;">
        Repérer les pays ou groupes de pays qui présentent un potentiel intéressant pour une future stratégie
        d’exportation de volaille.
      </p>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">📊 Approche data</div>
      <p style="margin:0;">
        Construire un dataset pays à partir d’indicateurs alimentaires, démographiques et commerciaux issus
        principalement des données FAO.
      </p>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">🌍 Finalité stratégique</div>
      <p style="margin:0;">
        Préparer une segmentation des pays afin d’aider le COMEX à prioriser les marchés à étudier plus en détail.
      </p>
    </div>
  </div>

  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.30);
  ">
    🧭 <b style="color:#FDE68A;">Démarche retenue :</b>
    <ul style="margin:8px 0 0 0; padding-left:20px;">
      <li>analyser les fichiers sources disponibles ;</li>
      <li>sélectionner au moins <b>8 variables pertinentes</b> pour la problématique ;</li>
      <li>nettoyer les données et retirer les pays peu exploitables ou aberrants ;</li>
      <li>créer des variables dérivées utiles à l’analyse ;</li>
      <li>exporter un dataset final propre pour l’ACP et le clustering.</li>
    </ul>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(168,85,247,0.08);
    border:1px solid rgba(168,85,247,0.28);
  ">
    👉 <b style="color:#D8B4FE;">En clair :</b><br>
    Ce premier notebook sert à construire une base fiable et cohérente. Le second notebook utilisera ensuite ce dataset
    pour réaliser l’ACP, le clustering et les recommandations de pays à prioriser.
  </div>

</div>

<a id="etape2"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(56,189,248,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(6,28,50,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(78%) sepia(40%) saturate(1318%) hue-rotate(166deg) brightness(101%) contrast(100%);
      ">
    </a>
    <span style="color:#FFFFFF;">🌍 Étape 2</span>
    <span>• Compréhension et sélection des variables</span>
  </h2>
</div>

<a id="etape2_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.1 • Lecture de la structure des fichiers</span>
  </h3>
</div>

In [375]:
# Liste des colonnes du fichier disponibilité alimentaire
dispo.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole'],
      dtype='str')

In [376]:
# Liste des colonnes du fichier population
population.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole', 'Note'],
      dtype='str')

In [377]:
# Nombre de pays présents dans chaque fichier
nb_pays_dispo = dispo["Zone"].nunique()
nb_pays_population = population["Zone"].nunique()

print(f"Nombre de pays dans le fichier disponibilité alimentaire : {nb_pays_dispo}")
print(f"Nombre de pays dans le fichier population : {nb_pays_population}")

Nombre de pays dans le fichier disponibilité alimentaire : 174
Nombre de pays dans le fichier population : 238

In [378]:
# Modalités disponibles dans la colonne Élément
dispo["Élément"].dropna().unique()

<StringArray>
[                                                   'Production',
                                       'Importations - Quantité',
                                            'Variation de stock',
                                       'Exportations - Quantité',
                                      'Disponibilité intérieure',
                                         'Aliments pour animaux',
                                                      'Semences',
                                                        'Pertes',
                                                       'Résidus',
                                                    'Nourriture',
        'Disponibilité alimentaire en quantité (kg/personne/an)',
                'Disponibilité alimentaire (Kcal/personne/jour)',
      'Disponibilité de protéines en quantité (g/personne/jour)',
 'Disponibilité de matière grasse en quantité (g/personne/jour)',
                                                    'Traitement',
                         'Autres utilisations (non alimentaire)',
                                   'Alimentation pour touristes']
Length: 17, dtype: str

In [379]:
# Modalités disponibles dans la colonne Produit
dispo["Produit"].dropna().unique()

<StringArray>
[                'Blé et produits',                 'Riz et produits',
                'Orge et produits',                'Maïs et produits',
              'Seigle et produits',                          'Avoine',
              'Millet et produits',              'Sorgho et produits',
                'Céréales, Autres',     'Pommes de Terre et produits',
                         'Ignames',                     'Racines nda',
                    'Sucre, canne',                'Sucre, betterave',
                   'Sucre Eq Brut',              'Edulcorants Autres',
                            'Miel',                        'Haricots',
                            'Pois', 'Légumineuses Autres et produits',
                'Noix et produits',                            'Soja',
          'Arachides Decortiquees',            'Graines de tournesol',
          'Graines Colza/Moutarde',                'Graines de coton',
              'Coco (Incl Coprah)',                          'Sésame',
                          'Olives',        'Plantes Oleiferes, Autre',
                   'Huile de Soja',                'Huile d'Arachide',
              'Huile de Tournesol',         'Huile de Colza&Moutarde',
          'Huile Graines de Coton',              'Huile de Palmistes',
                  'Huile de Palme',                   'Huile de Coco',
                 'Huile de Sésame',                   'Huile d'Olive',
             'Huile de Son de Riz',          'Huile de Germe de Maïs',
         'Huil Plantes Oleif Autr',             'Tomates et produits',
                         'Oignons',                 'Légumes, Autres',
             'Oranges, Mandarines',     'Citrons & Limes et produits',
        'Pamplemousse et produits',                 'Agrumes, Autres',
                         'Bananes',              'Pommes et produits',
              'Ananas et produits',                          'Dattes',
                          'Raisin',                  'Fruits, Autres',
                'Café et produits',       'Feve de Cacao et produits',
                             'Thé',                          'Poivre',
                         'Piments',                        'Girofles',
                  'Épices, Autres',                             'Vin',
                           'Bière',              'Boissons Fermentés',
            'Boissons Alcooliques',          'Alcool, non Comestible',
                'Viande de Bovins',          'Viande d'Ovins/Caprins',
                'Viande de Suides',             'Viande de Volailles',
                   'Viande, Autre',                'Abats Comestible',
                    'Beurre, Ghee',                           'Crème',
          'Graisses Animales Crue',                           'Oeufs',
              'Lait - Excl Beurre',              'Poissons Eau Douce',
           'Aliments pour enfants',                    'Miscellanees',
              'Manioc et produits',                  'Patates douces',
                       'Palmistes',               'Bananes plantains',
              'Huiles de Poissons',        'Huiles de Foie de Poisso',
                       'Perciform',             'Poissons Pelagiques',
         'Poissons Marins, Autres',                       'Crustacés',
                    'Cephalopodes',              'Mollusques, Autres',
        'Animaux Aquatiques Autre',              'Plantes Aquatiques',
            'Sucre non centrifugé',          'Viande de Anim Aquatiq']
Length: 98, dtype: str

In [380]:
# Nombre d'occurrences par élément
dispo["Élément"].value_counts()

Élément
Disponibilité intérieure                                         15905
Importations - Quantité                                          15260
Disponibilité alimentaire en quantité (kg/personne/an)           14618
Disponibilité de matière grasse en quantité (g/personne/jour)    14512
Disponibilité de protéines en quantité (g/personne/jour)         14507
Nourriture                                                       14498
Disponibilité alimentaire (Kcal/personne/jour)                   14476
Résidus                                                          12567
Exportations - Quantité                                          12113
Variation de stock                                               11299
Production                                                       10334
Pertes                                                            5813
Alimentation pour touristes                                       5560
Autres utilisations (non alimentaire)                             5292
Aliments pour animaux                                             4188
Traitement                                                        3546
Semences                                                          2112
Name: count, dtype: int64

In [381]:
# Nombre d'occurrences par produit
dispo["Produit"].value_counts().head(30)

Produit
Maïs et produits                   2593
Blé et produits                    2581
Pommes de Terre et produits        2486
Riz et produits                    2452
Lait - Excl Beurre                 2395
Oeufs                              2347
Légumineuses Autres et produits    2336
Orge et produits                   2301
Soja                               2222
Céréales, Autres                   2206
Légumes, Autres                    2204
Fruits, Autres                     2198
Arachides Decortiquees             2197
Edulcorants Autres                 2194
Haricots                           2141
Sucre Eq Brut                      2137
Graisses Animales Crue             2137
Feve de Cacao et produits          2088
Huil Plantes Oleif Autr            2083
Plantes Oleiferes, Autre           2077
Viande de Bovins                   2065
Viande de Volailles                2061
Avoine                             2060
Coco (Incl Coprah)                 2051
Tomates et produits                2046
Raisin                             2035
Graines Colza/Moutarde             2028
Oranges, Mandarines                2027
Viande de Suides                   2009
Pommes et produits                 2005
Name: count, dtype: int64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🔎</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.1 • Lecture de la structure des fichiers</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Cette étape permet de comprendre la structure des deux fichiers sources avant de sélectionner les variables utiles.
    Les fichiers disposent d’une organisation similaire : chaque ligne correspond à une combinaison
    <b style="color:#7DD3FC;">pays / produit / indicateur / année</b>.
  </p>

  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🍗 Fichier disponibilité alimentaire</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>174</b> pays identifiés</li>
        <li><b>17</b> types d’indicateurs disponibles</li>
        <li><b>98</b> produits alimentaires différents</li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(168,85,247,0.08);
      border:1px solid rgba(168,85,247,0.28);
    ">
      <div style="font-weight:700; color:#E9C7FF; margin-bottom:6px;">🌍 Fichier population</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>238</b> pays ou zones identifiés</li>
        <li>Données disponibles sur plusieurs années</li>
        <li>Unité exprimée en <b>1000 personnes</b></li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Constat principal :</b><br>
    Les deux fichiers contiennent une colonne <b>Zone</b>, ce qui permettra de les rapprocher par pays.
    Le fichier de disponibilité alimentaire contient également les colonnes <b>Produit</b> et <b>Élément</b>,
    indispensables pour filtrer les données liées à la volaille.
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.30);
  ">
    📌 <b style="color:#FDE68A;">Point d’attention :</b><br>
    Le nombre de pays est différent entre les deux fichiers. Il faudra donc vérifier, lors de la construction du dataset final,
    quels pays sont présents dans les deux sources et supprimer ceux pour lesquels les informations utiles sont incomplètes.
  </div>

  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(56,189,248,0.08);
    border:1px solid rgba(56,189,248,0.26);
  ">
    👉 <b style="color:#BFE9FF;">En clair :</b><br>
    Les données sont bien structurées pour construire une base d’analyse par pays. La suite consiste à identifier
    les produits liés à la volaille et les indicateurs les plus pertinents pour répondre à la problématique d’exportation.
  </div>

</div>

<a id="etape2_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.2 • Réflexion PESTEL appliquée au projet</span>
  </h3>
</div>

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🌐</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.2 • Réflexion PESTEL appliquée au projet</b>
  </div>
  <p style="margin:0 0 14px 0;">
    Avant de sélectionner les variables, une réflexion PESTEL permet de cadrer les dimensions utiles à une stratégie
    d’exportation. Toutes les dimensions ne sont pas directement mesurables avec les fichiers FAO, mais elles permettent
    de justifier les indicateurs retenus.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="padding:12px 2px; border-radius:12px; background:rgba(236,72,153,0.08); border:1px solid rgba(236,72,153,0.28);">
      <div style="font-weight:700; color:#F9A8D4; margin-bottom:6px;">🏛️ Politique</div>
      <p style="margin:0;">La stabilité politique, les réglementations sanitaires et les barrières douanières peuvent influencer la capacité d’une entreprise à exporter.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(250,204,21,0.08); border:1px solid rgba(250,204,21,0.28);">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">💰 Économique</div>
      <p style="margin:0;">Le niveau d’importation, la production locale et la dépendance aux importations permettent d’évaluer l’attractivité d’un marché.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(34,197,94,0.08); border:1px solid rgba(34,197,94,0.28);">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">👥 Sociodémographique</div>
      <p style="margin:0;">La taille de la population et les habitudes alimentaires permettent d’estimer le potentiel de demande.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(56,189,248,0.08); border:1px solid rgba(56,189,248,0.28);">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🚚 Technologique</div>
      <p style="margin:0;">La logistique, la distribution et la chaîne du froid peuvent influencer la faisabilité d’une stratégie d’exportation.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(132,204,22,0.08); border:1px solid rgba(132,204,22,0.28);">
      <div style="font-weight:700; color:#BEF264; margin-bottom:6px;">🌱 Environnemental</div>
      <p style="margin:0;">La capacité de production locale, les contraintes climatiques et les ressources disponibles peuvent influencer le besoin d’importation.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(168,85,247,0.08); border:1px solid rgba(168,85,247,0.28);">
      <div style="font-weight:700; color:#E9C7FF; margin-bottom:6px;">⚖️ Légal</div>
      <p style="margin:0;">Les normes sanitaires, les accords commerciaux et les règles d’importation peuvent impacter la faisabilité de l’exportation.</p>
    </div>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(56,189,248,0.08);
    border:1px solid rgba(56,189,248,0.28);
  ">
    👉 <b style="color:#BFE9FF;">En clair :</b><br>
    Dans ce notebook, l’analyse se concentre surtout sur les dimensions <b>alimentaires</b>,
    <b>économiques</b> et <b>démographiques</b>, car ce sont celles qui sont directement exploitables
    à partir des données disponibles.
  </div>

</div>

<a id="etape2_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.3 • Sélection des variables pertinentes</span>
  </h3>
</div>

In [382]:
# Liste des indicateurs disponibles dans les données FAO
elements_disponibles = sorted(dispo["Élément"].dropna().unique())

for element in elements_disponibles:
    print(element)

Alimentation pour touristes
Aliments pour animaux
Autres utilisations (non alimentaire)
Disponibilité alimentaire (Kcal/personne/jour)
Disponibilité alimentaire en quantité (kg/personne/an)
Disponibilité de matière grasse en quantité (g/personne/jour)
Disponibilité de protéines en quantité (g/personne/jour)
Disponibilité intérieure
Exportations - Quantité
Importations - Quantité
Nourriture
Pertes
Production
Résidus
Semences
Traitement
Variation de stock

In [383]:
# Identification des produits liés à la volaille
produits_volaille = dispo[
    dispo["Produit"].str.contains("volaille|poulet|viande de volailles", case=False, na=False)
]["Produit"].unique()

produits_volaille

<StringArray>
['Viande de Volailles']
Length: 1, dtype: str

In [384]:
# Filtrage des données liées à la viande de volailles
volaille = dispo[dispo["Produit"] == "Viande de Volailles"].copy()

print("Dimensions du sous-ensemble volaille :", volaille.shape)
volaille.head()

Dimensions du sous-ensemble volaille : (2061, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.00,S,Données standardisées

In [385]:
# Indicateurs disponibles pour la viande de volailles
volaille["Élément"].value_counts()

Élément
Disponibilité alimentaire en quantité (kg/personne/an)           172
Disponibilité alimentaire (Kcal/personne/jour)                   172
Disponibilité de protéines en quantité (g/personne/jour)         172
Disponibilité de matière grasse en quantité (g/personne/jour)    172
Importations - Quantité                                          170
Disponibilité intérieure                                         170
Nourriture                                                       170
Variation de stock                                               169
Production                                                       168
Résidus                                                          164
Exportations - Quantité                                          135
Alimentation pour touristes                                       78
Pertes                                                            67
Traitement                                                        46
Autres utilisations (non alimentaire)                             34
Aliments pour animaux                                              1
Semences                                                           1
Name: count, dtype: int64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🎯</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.3 • Sélection des variables pertinentes</b>
  </div>

  <p style="margin:0 0 12px 0;">
    La sélection des variables commence par l’identification du produit correspondant à la problématique métier :
    <b style="color:#FDE68A;">Viande de Volailles</b>. Ce sous-ensemble servira de base pour construire les indicateurs
    utiles à l’analyse de marché.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:4px 4px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🍗 Produit ciblé</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Produit identifié : <b>Viande de Volailles</b></li>
        <li>Sous-ensemble obtenu : <b>2 061</b> lignes</li>
        <li>Données disponibles sur plusieurs indicateurs FAO</li>
      </ul>
    </div>
    <div style="
      padding:4px 4px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">📊 Indicateurs clés disponibles</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Disponibilité alimentaire</li>
        <li>Production</li>
        <li>Importations / exportations</li>
        <li>Disponibilité intérieure</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.30);
  ">
    📌 <b style="color:#FDE68A;">Lecture des données :</b><br>
    Les indicateurs les plus complets pour la viande de volailles concernent la disponibilité alimentaire
    en quantité, en calories, en protéines et en matières grasses. Les indicateurs commerciaux et productifs
    comme les importations, la production, les exportations et la disponibilité intérieure sont également disponibles.
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Le produit cible est bien présent dans les données. Les indicateurs disponibles permettent de construire une base
    cohérente pour évaluer à la fois le potentiel de consommation, le niveau de production locale et la dépendance
    potentielle aux importations.
  </div>
</div>

<a id="etape2_3_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.3.1 • Repérage des pays à faible couverture</span>
  </h3>
</div>

In [386]:
# Liste des indicateurs FAO retenus à ce stade
elements_retenus = [
    "Disponibilité alimentaire (Kcal/personne/jour)",
    "Disponibilité alimentaire en quantité (kg/personne/an)",
    "Disponibilité de protéines en quantité (g/personne/jour)",
    "Disponibilité de matière grasse en quantité (g/personne/jour)",
    "Importations - Quantité",
    "Production",
    "Exportations - Quantité",
    "Disponibilité intérieure"
]

elements_retenus

['Disponibilité alimentaire (Kcal/personne/jour)',
 'Disponibilité alimentaire en quantité (kg/personne/an)',
 'Disponibilité de protéines en quantité (g/personne/jour)',
 'Disponibilité de matière grasse en quantité (g/personne/jour)',
 'Importations - Quantité',
 'Production',
 'Exportations - Quantité',
 'Disponibilité intérieure']

In [387]:
# Sous-ensemble volaille limité aux indicateurs FAO retenus
volaille_selected = volaille[
    volaille["Élément"].isin(elements_retenus)
].copy()

print("Dimensions après sélection :", volaille_selected.shape)
volaille_selected.head()

Dimensions après sélection : (1331, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
658,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/personne/an),2734,Viande de Volailles,2017,2017,kg,1.53,Fc,Donnée calculée
659,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2017,2017,Kcal/personne/jour,5.00,Fc,Donnée calculée

In [388]:
# Nombre d'indicateurs disponibles par pays
nb_indicateurs_par_pays = (
    volaille_selected.groupby("Zone")["Élément"]
    .nunique()
    .sort_values()
)

nb_indicateurs_par_pays.head(30)

Zone
Ouzbékistan                              4
République démocratique populaire lao    4
Maldives                                 6
Djibouti                                 6
Cambodge                                 7
Cabo Verde                               7
Bahamas                                  7
Afghanistan                              7
Guinée-Bissau                            7
Gambie                                   7
Guinée                                   7
Grenade                                  7
Haïti                                    7
Kiribati                                 7
Cuba                                     7
Bangladesh                               7
Madagascar                               7
Mauritanie                               7
Mozambique                               7
Malawi                                   7
Nouvelle-Calédonie                       7
Népal                                    7
République centrafricaine                7
Mongolie                                 7
Mali                                     7
Timor-Leste                              7
Sao Tomé-et-Principe                     7
Soudan                                   7
République-Unie de Tanzanie              7
Saint-Vincent-et-les Grenadines          7
Name: Élément, dtype: int64

In [389]:
# Pays avec moins que le nombre total d'indicateurs retenus
pays_incomplets = nb_indicateurs_par_pays[
    nb_indicateurs_par_pays < len(elements_retenus)
]

pays_incomplets

Zone
Ouzbékistan                              4
République démocratique populaire lao    4
Maldives                                 6
Djibouti                                 6
Cambodge                                 7
Cabo Verde                               7
Bahamas                                  7
Afghanistan                              7
Guinée-Bissau                            7
Gambie                                   7
Guinée                                   7
Grenade                                  7
Haïti                                    7
Kiribati                                 7
Cuba                                     7
Bangladesh                               7
Madagascar                               7
Mauritanie                               7
Mozambique                               7
Malawi                                   7
Nouvelle-Calédonie                       7
Népal                                    7
République centrafricaine                7
Mongolie                                 7
Mali                                     7
Timor-Leste                              7
Sao Tomé-et-Principe                     7
Soudan                                   7
République-Unie de Tanzanie              7
Saint-Vincent-et-les Grenadines          7
Sainte-Lucie                             7
Burkina Faso                             7
Tadjikistan                              7
Zimbabwe                                 7
Éthiopie                                 7
Turkménistan                             7
Vanuatu                                  7
Name: Élément, dtype: int64

In [390]:
# Nombre de pays complets vs incomplets
nb_pays_complets = (nb_indicateurs_par_pays == len(elements_retenus)).sum()
nb_pays_incomplets = (nb_indicateurs_par_pays < len(elements_retenus)).sum()

print("Nombre de pays complets :", nb_pays_complets)
print("Nombre de pays incomplets :", nb_pays_incomplets)

Nombre de pays complets : 135
Nombre de pays incomplets : 37

In [391]:
# Répartition du nombre d'indicateurs par pays
nb_indicateurs_par_pays.value_counts().sort_index()

Élément
4      2
6      2
7     33
8    135
Name: count, dtype: int64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(10,45,78,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">📊</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.3.1 — Repérage des pays à faible couverture</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Avant même le nettoyage, une première vérification de la couverture des données par pays permet d’identifier
    les zones pour lesquelles l’information disponible est incomplète. Cette étape est importante car un pays
    mal renseigné peut fragiliser ou biaiser les analyses ultérieures.
  </p>

  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Pays complets</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>135 pays</b> disposent des <b>8 indicateurs</b> retenus</li>
        <li>Ces pays constituent la base la plus robuste pour la suite</li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(250,204,21,0.08);
      border:1px solid rgba(250,204,21,0.28);
    ">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">⚠️ Pays incomplets</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>37 pays</b> n’ont pas tous les indicateurs</li>
        <li>Ils devront être surveillés avant la construction du dataset final</li>
      </ul>
    </div>
  </div>

  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(255,255,255,0.03);
    border:1px solid rgba(191,233,255,0.20);
  ">
    <div style="font-weight:700; color:#BFE9FF; margin-bottom:8px;">📌 Répartition observée</div>
    <ul style="margin:0; padding-left:18px;">
      <li><b>2 pays</b> avec seulement <b>4 indicateurs</b></li>
      <li><b>2 pays</b> avec <b>6 indicateurs</b></li>
      <li><b>33 pays</b> avec <b>7 indicateurs</b></li>
      <li><b>135 pays</b> avec les <b>8 indicateurs</b></li>
    </ul>
  </div>

  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    📍 <b style="color:#F9A8D4;">Lecture analytique :</b><br>
    La majorité des pays sont bien couverts, ce qui est rassurant pour la suite du projet. En revanche, une partie du périmètre
    présente une couverture incomplète. Ces cas devront être examinés plus finement, notamment lorsqu’ils concernent des territoires
    de petite taille ou des zones peu pertinentes pour une stratégie d’exportation internationale.
  </div>

  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    👉 <b style="color:#86EFAC;">En clair :</b><br>
    Cette étape montre qu’avant même le nettoyage, tous les pays ne disposent pas du même niveau d’information.
    La suite du travail consistera à identifier précisément quels territoires doivent être écartés pour conserver
    un dataset à la fois cohérent, lisible et exploitable.
  </div>
</div>

<a id="etape2_3_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.3.2 • Identification des petites îles et territoires atypiques</span>
  </h3>
</div>

In [392]:
# Population 2017 uniquement
population_2017 = population[
    population["Année"] == 2017
].copy()

population_2017["Valeur"] = pd.to_numeric(population_2017["Valeur"], errors="coerce")
population_2017["Valeur"] = population_2017["Valeur"] * 1_000
population_2017["Unité"] = "personnes"

print("Dimensions population_2017 :", population_2017.shape)
population_2017.head()

Dimensions population_2017 : (236, 15)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
17,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2017,2017,personnes,36.30 millions,X,Sources internationales sûres,NaN
36,OA,Séries temporelles annuelles,202,Afrique du Sud,511,Population totale,3010,Population-Estimations,2017,2017,personnes,57.01 millions,X,Sources internationales sûres,NaN
55,OA,Séries temporelles annuelles,3,Albanie,511,Population totale,3010,Population-Estimations,2017,2017,personnes,2.88 millions,X,Sources internationales sûres,NaN
74,OA,Séries temporelles annuelles,4,Algérie,511,Population totale,3010,Population-Estimations,2017,2017,personnes,41.39 millions,X,Sources internationales sûres,NaN
93,OA,Séries temporelles annuelles,79,Allemagne,511,Population totale,3010,Population-Estimations,2017,2017,personnes,82.66 millions,X,Sources internationales sûres,NaN

In [393]:
# Tableau simplifié population
population_2017_simple = population_2017[["Zone", "Valeur"]].copy()
population_2017_simple = population_2017_simple.rename(columns={"Valeur": "population_2017"})

population_2017_simple.head()

              Zone  population_2017
17     Afghanistan   36.30 millions
36  Afrique du Sud   57.01 millions
55         Albanie    2.88 millions
74         Algérie   41.39 millions
93       Allemagne   82.66 millions

In [394]:
# Pays / territoires les moins peuplés
population_2017_simple.sort_values(by="population_2017").head(30)

                                              Zone  population_2017
3672                                   Saint-Siège           793.00
4143                                      Tokélaou            1 300
2896                                         Nioué            1 609
1781                      Îles Falkland (Malvinas)            3 068
2725                                    Montserrat            4 984
3653                      Saint-Pierre-et-Miquelon            5 887
3569  Sainte-Hélène, Ascension et Tristan da Cunha            6 008
3550                              Saint-Barthélemy            9 784
2801                                         Nauru           10 573
4257                                        Tuvalu           11 370
1933                         Îles Wallis-et-Futuna           11 900
150                                       Anguilla           14 584
1762                                     Îles Cook           17 507
3048                                        Palaos           17 808
538                Bonaire, Saint-Eustache et Saba           25 401
1914                     Îles Vierges britanniques           29 577
3626                                   Saint-Marin           33 671
1420                                     Gibraltar           33 728
3634               Saint-Martin (partie française)           36 560
1876                       Îles Turques-et-Caïques           37 115
2351                                 Liechtenstein           37 800
2674                                        Monaco           38 392
3851           Sint Maarten  (partie néerlandaise)           41 444
1800                                    Îles Féroé           48 331
3607                          Saint-Kitts-et-Nevis           52 045
3729                             Samoa américaines           55 620
1477                                     Groenland           56 481
1819                        Îles Mariannes du Nord           56 562
1838                                 Îles Marshall           58 058
492                                       Bermudes           63 049

In [395]:
# Fusion couverture + population
df_couverture_population = nb_indicateurs_par_pays.reset_index()
df_couverture_population.columns = ["Zone", "nb_indicateurs"]

df_couverture_population = df_couverture_population.merge(
    population_2017_simple,
    on="Zone",
    how="left"
)

df_couverture_population.sort_values(
    by=["nb_indicateurs", "population_2017"],
    ascending=[True, True]
).head(30)

                                     Zone  nb_indicateurs  population_2017
1   République démocratique populaire lao               4    6.95 millions
0                             Ouzbékistan               4   31.96 millions
2                                Maldives               6          496 402
3                                Djibouti               6          944 099
29        Saint-Vincent-et-les Grenadines               7          109 827
11                                Grenade               7          110 874
13                               Kiribati               7          114 158
30                           Sainte-Lucie               7          180 954
26                   Sao Tomé-et-Principe               7          207 089
20                     Nouvelle-Calédonie               7          277 150
36                                Vanuatu               7          285 510
6                                 Bahamas               7          381 755
5                              Cabo Verde               7          537 498
25                            Timor-Leste               7    1.24 millions
8                           Guinée-Bissau               7    1.83 millions
9                                  Gambie               7    2.21 millions
23                               Mongolie               7    3.11 millions
17                             Mauritanie               7    4.28 millions
22              République centrafricaine               7    4.60 millions
35                           Turkménistan               7    5.76 millions
32                            Tadjikistan               7    8.88 millions
12                                  Haïti               7   10.98 millions
14                                   Cuba               7   11.34 millions
10                                 Guinée               7   12.07 millions
33                               Zimbabwe               7   14.24 millions
4                                Cambodge               7   16.01 millions
19                                 Malawi               7   17.67 millions
24                                   Mali               7   18.51 millions
31                           Burkina Faso               7   19.19 millions
16                             Madagascar               7   25.57 millions

In [396]:
# Liste indicative de territoires / petites îles à surveiller
territoires_a_surveiller = [
    "Saint-Siège",
    "Tokélaou",
    "Nioué",
    "Îles Falkland (Malvinas)",
    "Montserrat",
    "Saint-Pierre-et-Miquelon",
    "Sainte-Hélène, Ascension et Tristan da Cunha",
    "Saint-Barthélemy",
    "Nauru",
    "Tuvalu",
    "Îles Wallis-et-Futuna",
    "Anguilla",
    "Îles Cook",
    "Palaos",
    "Îles Vierges britanniques",
    "Saint-Marin",
    "Gibraltar",
    "Saint-Martin (partie française)",
    "Îles Turques-et-Caïques",
    "Liechtenstein",
    "Monaco",
    "Sint Maarten (partie néerlandaise)",
    "Îles Féroé",
    "Saint-Kitts-et-Nevis",
    "Samoa américaines",
    "Groenland",
    "Îles Mariannes du Nord",
    "Îles Marshall",
    "Bermudes",
    "Kiribati",
    "Maldives",
    "Vanuatu",
    "Cabo Verde",
    "Nouvelle-Calédonie",
    "São Tomé-et-Principe",
    "Saint-Vincent-et-les Grenadines",
    "Sainte-Lucie"
]

territoires_a_surveiller

['Saint-Siège',
 'Tokélaou',
 'Nioué',
 'Îles Falkland (Malvinas)',
 'Montserrat',
 'Saint-Pierre-et-Miquelon',
 'Sainte-Hélène, Ascension et Tristan da Cunha',
 'Saint-Barthélemy',
 'Nauru',
 'Tuvalu',
 'Îles Wallis-et-Futuna',
 'Anguilla',
 'Îles Cook',
 'Palaos',
 'Îles Vierges britanniques',
 'Saint-Marin',
 'Gibraltar',
 'Saint-Martin (partie française)',
 'Îles Turques-et-Caïques',
 'Liechtenstein',
 'Monaco',
 'Sint Maarten (partie néerlandaise)',
 'Îles Féroé',
 'Saint-Kitts-et-Nevis',
 'Samoa américaines',
 'Groenland',
 'Îles Mariannes du Nord',
 'Îles Marshall',
 'Bermudes',
 'Kiribati',
 'Maldives',
 'Vanuatu',
 'Cabo Verde',
 'Nouvelle-Calédonie',
 'São Tomé-et-Principe',
 'Saint-Vincent-et-les Grenadines',
 'Sainte-Lucie']

In [397]:
# Territoires / petites îles repérés dans le tableau fusionné
df_territoires_a_surveiller = df_couverture_population[
    df_couverture_population["Zone"].isin(territoires_a_surveiller)
].sort_values(
    by=["nb_indicateurs", "population_2017"],
    ascending=[True, True]
)

df_territoires_a_surveiller

                                Zone  nb_indicateurs  population_2017
2                           Maldives               6          496 402
29   Saint-Vincent-et-les Grenadines               7          109 827
13                          Kiribati               7          114 158
30                      Sainte-Lucie               7          180 954
20                Nouvelle-Calédonie               7          277 150
36                           Vanuatu               7          285 510
5                         Cabo Verde               7          537 498
141             Saint-Kitts-et-Nevis               8           52 045

In [398]:
# Nombre de territoires surveillés incomplets
territoires_incomplets = df_territoires_a_surveiller[
    df_territoires_a_surveiller["nb_indicateurs"] < len(elements_retenus)
]

print("Nombre de territoires surveillés :", df_territoires_a_surveiller.shape[0])
print("Nombre de territoires surveillés incomplets :", territoires_incomplets.shape[0])

Nombre de territoires surveillés : 8
Nombre de territoires surveillés incomplets : 7

In [399]:
# Territoires surveillés avec moins de 1 million d'habitants
territoires_faible_population = df_territoires_a_surveiller[
    df_territoires_a_surveiller["population_2017"] < 1_000_000
]

print("Nombre de territoires surveillés avec moins de 1 million d'habitants :", territoires_faible_population.shape[0])
territoires_faible_population

Nombre de territoires surveillés avec moins de 1 million d'habitants : 8

                                Zone  nb_indicateurs  population_2017
2                           Maldives               6          496 402
29   Saint-Vincent-et-les Grenadines               7          109 827
13                          Kiribati               7          114 158
30                      Sainte-Lucie               7          180 954
20                Nouvelle-Calédonie               7          277 150
36                           Vanuatu               7          285 510
5                         Cabo Verde               7          537 498
141             Saint-Kitts-et-Nevis               8           52 045

In [400]:
# Première liste technique de zones candidates à une exclusion future
zones_candidates_exclusion = df_territoires_a_surveiller[
    (df_territoires_a_surveiller["population_2017"] < 1_000_000) |
    (df_territoires_a_surveiller["nb_indicateurs"] < len(elements_retenus))
]["Zone"].tolist()

zones_candidates_exclusion

['Maldives',
 'Saint-Vincent-et-les Grenadines',
 'Kiribati',
 'Sainte-Lucie',
 'Nouvelle-Calédonie',
 'Vanuatu',
 'Cabo Verde',
 'Saint-Kitts-et-Nevis']

In [401]:
# Nombre de zones candidates à l'exclusion
print("Nombre de zones candidates à l'exclusion :", len(zones_candidates_exclusion))

Nombre de zones candidates à l'exclusion : 8

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(10,45,78,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🏝️</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.3.2 — Identification des petites îles et territoires atypiques</b>
  </div>

  <p style="margin:0 0 12px 0;">
    En complément de l’analyse de couverture, un croisement avec la population 2017 a permis de repérer les zones
    de très petite taille démographique. Ces territoires, souvent insulaires ou atypiques, peuvent être peu représentatifs
    d’une stratégie d’expansion internationale et risquent de fragiliser le périmètre d’analyse.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Résultat principal</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>8 territoires</b> ont été identifiés comme candidats à une exclusion future</li>
        <li>Ils présentent tous une <b>population inférieure à 1 million d’habitants</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(250,204,21,0.08);
      border:1px solid rgba(250,204,21,0.28);
    ">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">⚠️ Lecture métier</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Ces zones sont de très petite taille</li>
        <li>Elles sont susceptibles de biaiser la construction d’un dataset pays robuste</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(255,255,255,0.03);
    border:1px solid rgba(191,233,255,0.20);
  ">
    <div style="font-weight:700; color:#BFE9FF; margin-bottom:8px;">📌 Territoires repérés à ce stade</div>
    <ul style="columns:2; -webkit-columns:2; -moz-columns:2; margin:0; padding-left:18px;">
      <li>Maldives</li>
      <li>Saint-Vincent-et-les Grenadines</li>
      <li>Kiribati</li>
      <li>Sainte-Lucie</li>
      <li>Nouvelle-Calédonie</li>
      <li>Vanuatu</li>
      <li>Cabo Verde</li>
      <li>Saint-Kitts-et-Nevis</li>
    </ul>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    📍 <b style="color:#F9A8D4;">Interprétation :</b><br>
    À ce stade, ces territoires ne sont pas encore retirés du jeu de données. En revanche, ils sont clairement identifiés
    comme des cas spécifiques à surveiller, car leur faible poids démographique peut rendre l’analyse moins représentative
    d’une logique d’exportation internationale à grande échelle.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    👉 <b style="color:#86EFAC;">En clair :</b><br>
    Cette étape permet de préparer la future phase de nettoyage. Les territoires de très petite taille démographique,
    bien que présents dans les sources, pourront être exclus en section 3 afin de conserver un périmètre d’analyse plus homogène,
    plus lisible et plus pertinent pour la prise de décision.
  </div>
</div>

<a id="etape2_4"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.4 • Justification métier des variables retenues</span>
  </h3>
</div>

In [402]:
# Première sélection d'indicateurs pertinents pour l'analyse
elements_retenus = [
    "Disponibilité alimentaire (Kcal/personne/jour)",
    "Disponibilité alimentaire en quantité (kg/personne/an)",
    "Disponibilité de protéines en quantité (g/personne/jour)",
    "Disponibilité de matière grasse en quantité (g/personne/jour)",
    "Importations - Quantité",
    "Production",
    "Exportations - Quantité",
    "Disponibilité intérieure"
]

elements_retenus

['Disponibilité alimentaire (Kcal/personne/jour)',
 'Disponibilité alimentaire en quantité (kg/personne/an)',
 'Disponibilité de protéines en quantité (g/personne/jour)',
 'Disponibilité de matière grasse en quantité (g/personne/jour)',
 'Importations - Quantité',
 'Production',
 'Exportations - Quantité',
 'Disponibilité intérieure']

In [403]:
# Vérification de la présence des indicateurs retenus dans le fichier
elements_existants = dispo["Élément"].unique()

for element in elements_retenus:
    if element in elements_existants:
        print(f"✅ Présent : {element}")
    else:
        print(f"❌ Absent ou nom différent : {element}")

✅ Présent : Disponibilité alimentaire (Kcal/personne/jour)
✅ Présent : Disponibilité alimentaire en quantité (kg/personne/an)
✅ Présent : Disponibilité de protéines en quantité (g/personne/jour)
✅ Présent : Disponibilité de matière grasse en quantité (g/personne/jour)
✅ Présent : Importations - Quantité
✅ Présent : Production
✅ Présent : Exportations - Quantité
✅ Présent : Disponibilité intérieure

In [404]:
# Sélection des données volaille correspondant aux indicateurs retenus
volaille_selected = volaille[volaille["Élément"].isin(elements_retenus)].copy()

print("Dimensions après sélection :", volaille_selected.shape)
volaille_selected.head()

Dimensions après sélection : (1331, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
658,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/personne/an),2734,Viande de Volailles,2017,2017,kg,1.53,Fc,Donnée calculée
659,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2017,2017,Kcal/personne/jour,5.00,Fc,Donnée calculée

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧩</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.4 • Justification métier des variables retenues</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Une première sélection de variables a été réalisée afin de conserver les indicateurs les plus utiles pour une
    stratégie d’exportation de volaille. Ces variables seront ensuite nettoyées, transformées et complétées par des
    variables dérivées.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(280px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 4px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">🥗 Consommation et disponibilité</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Disponibilité alimentaire en quantité</li>
        <li>Disponibilité alimentaire en kcal</li>
        <li>Disponibilité en protéines</li>
        <li>Disponibilité en matières grasses</li>
      </ul>
    </div>
    <div style="
      padding:12px 4px;
      border-radius:12px;
      background:rgba(250,204,21,0.08);
      border:1px solid rgba(250,204,21,0.28);
    ">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">🏭 Offre locale et commerce</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Production</li>
        <li>Importations - Quantité</li>
        <li>Exportations - Quantité</li>
        <li>Disponibilité intérieure</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(56,189,248,0.08);
    border:1px solid rgba(56,189,248,0.28);
  ">
    ✅ <b style="color:#BFE9FF;">Contrôle de présence :</b><br>
    Les <b>8 indicateurs sélectionnés</b> sont bien présents dans le fichier FAO. Après filtrage sur la viande de volailles
    et les indicateurs retenus, le sous-ensemble contient <b>1 331</b> lignes.
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(168,85,247,0.08);
    border:1px solid rgba(168,85,247,0.28);
  ">
    🧠 <b style="color:#E9C7FF;">Pourquoi ces variables ?</b><br>
    Elles permettent de mesurer plusieurs dimensions complémentaires :
    <ul style="margin:8px 0 0 0; padding-left:20px;">
      <li>le potentiel de consommation de volaille ;</li>
      <li>la place de la volaille dans l’alimentation ;</li>
      <li>la capacité de production locale ;</li>
      <li>la dépendance potentielle aux importations ;</li>
      <li>le profil commercial du pays sur ce produit.</li>
    </ul>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Cette sélection constitue une première base solide pour construire le dataset final. Les variables seront ensuite
    pivotées par pays, croisées avec la population, puis enrichies avec des indicateurs dérivés comme le taux de dépendance
    aux importations ou le taux d’autosuffisance.
  </div>

</div>

<a id="etape3"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(251,146,60,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(48,21,6,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(74%) sepia(53%) saturate(1536%) hue-rotate(340deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span style="color:#FFFFFF;">🧹 Étape 3</span>
    <span>• Préparation et nettoyage des données</span>
  </h2>
</div>

<a id="etape3_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.1 • Pivot des données par pays</span>
  </h3>
</div>

In [405]:
# Contrôle du sous-ensemble avant pivot
print("Dimensions du sous-ensemble avant pivot :", volaille_selected.shape)
print("Nombre de pays :", volaille_selected["Zone"].nunique())
print("Indicateurs présents :")
print(sorted(volaille_selected["Élément"].unique()))

Dimensions du sous-ensemble avant pivot : (1331, 14)
Nombre de pays : 172
Indicateurs présents :
['Disponibilité alimentaire (Kcal/personne/jour)', 'Disponibilité alimentaire en quantité (kg/personne/an)', 'Disponibilité de matière grasse en quantité (g/personne/jour)', 'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité intérieure', 'Exportations - Quantité', 'Importations - Quantité', 'Production']

In [406]:
# Pivot des données FAO par pays
df_pivot_fao = volaille_selected.pivot_table(
    index="Zone",
    columns="Élément",
    values="Valeur",
    aggfunc="first"
).reset_index()

print("Dimensions après pivot :", df_pivot_fao.shape)
display(df_pivot_fao.head())

Dimensions après pivot : (172, 9)

Élément,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production
0,Afghanistan,5.00,1.53,0.33,0.54,57.00,NaN,29.00,28.00
1,Afrique du Sud,143.00,35.69,9.25,14.11,2 118,63.00,514.00,1 667
2,Albanie,85.00,16.36,6.45,6.26,47.00,0.00,38.00,13.00
3,Algérie,22.00,6.38,1.50,1.97,277.00,0.00,2.00,275.00
4,Allemagne,71.00,19.47,4.16,7.96,1 739,646.00,842.00,1 514

In [407]:
# Nettoyage léger des noms de colonnes
df_pivot_fao.columns.name = None

print("Colonnes du dataset pivoté :")
print(df_pivot_fao.columns.tolist())

Colonnes du dataset pivoté :
['Zone', 'Disponibilité alimentaire (Kcal/personne/jour)', 'Disponibilité alimentaire en quantité (kg/personne/an)', 'Disponibilité de matière grasse en quantité (g/personne/jour)', 'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité intérieure', 'Exportations - Quantité', 'Importations - Quantité', 'Production']

In [408]:
# Vérification du périmètre après pivot
print("Nombre de pays après pivot :", df_pivot_fao["Zone"].nunique())
print("Nombre total de colonnes :", df_pivot_fao.shape[1])

Nombre de pays après pivot : 172
Nombre total de colonnes : 9

In [409]:
# Valeurs manquantes après pivot
missing_pivot = df_pivot_fao.isnull().sum().sort_values(ascending=False)
display(missing_pivot[missing_pivot > 0])

Exportations - Quantité     37
Production                   4
Importations - Quantité      2
Disponibilité intérieure     2
dtype: int64

In [410]:
# Base de travail pour la suite de l'analyse
df_analysis_base = df_pivot_fao.copy()

print("Base d'analyse créée :", df_analysis_base.shape)
display(df_analysis_base.head())

Base d'analyse créée : (172, 9)

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production
0,Afghanistan,5.00,1.53,0.33,0.54,57.00,NaN,29.00,28.00
1,Afrique du Sud,143.00,35.69,9.25,14.11,2 118,63.00,514.00,1 667
2,Albanie,85.00,16.36,6.45,6.26,47.00,0.00,38.00,13.00
3,Algérie,22.00,6.38,1.50,1.97,277.00,0.00,2.00,275.00
4,Allemagne,71.00,19.47,4.16,7.96,1 739,646.00,842.00,1 514

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🏠</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.1 • Pivot des données par pays</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Les données FAO ont été restructurées en <b>format pays × indicateurs</b> afin d’obtenir une base plus lisible et directement exploitable
    pour les analyses multivariées. Chaque ligne correspond désormais à <b>un pays</b> et chaque colonne à <b>un indicateur retenu</b>.
  </p>

  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">📊 Structure du dataset pivoté</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>172 pays</b> conservés après pivot</li>
        <li><b>9 colonnes</b> au total</li>
        <li><b>1 colonne Zone + 8 indicateurs métiers</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🧩 Indicateurs présents</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Disponibilité alimentaire (Kcal/personne/jour)</li>
        <li>Disponibilité alimentaire en quantité (kg/personne/an)</li>
        <li>Disponibilité de matière grasse en quantité (g/personne/jour)</li>
        <li>Disponibilité de protéines en quantité (g/personne/jour)</li>
        <li>Disponibilité intérieure</li>
        <li>Exportations - Quantité</li>
        <li>Importations - Quantité</li>
        <li>Production</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    ⚠️ <b style="color:#FDE68A;">Point de vigilance :</b><br>
    Le pivot fait apparaître quelques <b>valeurs manquantes résiduelles</b>, principalement sur
    <b>Exportations - Quantité (37)</b>, puis <b>Production (4)</b>, <b>Importations - Quantité (2)</b> et
    <b>Disponibilité intérieure (2)</b>.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">En clair :</b><br>
    Cette transformation constitue une étape structurante du projet : on passe d’un fichier “long” à une structure “large”
    adaptée aux futures analyses statistiques, aux fusions avec les autres sources, puis à l’ACP/clustering.
  </div>
</div>

<a id="etape3_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.2 • Filtrage des indicateurs utiles</span>
  </h3>
</div>

In [411]:
# Copie de travail des datasets sources
dispo_clean = dispo.copy()
population_clean = population.copy()

print("✅ Copies de travail créées.")

✅ Copies de travail créées.

In [412]:
# Vérification rapide des années disponibles
print("Années disponibles dans le fichier disponibilité alimentaire :")
print(sorted(dispo_clean["Année"].unique())[:10], "...")

print("\nAnnées disponibles dans le fichier population :")
print(sorted(population_clean["Année"].unique())[-10:])

Années disponibles dans le fichier disponibilité alimentaire :
[np.int64(2017)] ...

Années disponibles dans le fichier population :
[np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018)]

In [413]:
# Filtrage de la population sur l'année 2017
population_2017 = population_clean[population_clean["Année"] == 2017].copy()

print("Dimensions du fichier population 2017 :", population_2017.shape)
population_2017.head()

Dimensions du fichier population 2017 : (236, 15)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
17,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,36 296,X,Sources internationales sûres,NaN
36,OA,Séries temporelles annuelles,202,Afrique du Sud,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,57 010,X,Sources internationales sûres,NaN
55,OA,Séries temporelles annuelles,3,Albanie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,2 884,X,Sources internationales sûres,NaN
74,OA,Séries temporelles annuelles,4,Algérie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,41 389,X,Sources internationales sûres,NaN
93,OA,Séries temporelles annuelles,79,Allemagne,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,82 658,X,Sources internationales sûres,NaN

In [414]:
# Vérification du type de produit retenu
produits_volaille = dispo_clean[
    dispo_clean["Produit"].str.contains("volaille|poulet|viande de volailles", case=False, na=False)
]["Produit"].unique()

produits_volaille

<StringArray>
['Viande de Volailles']
Length: 1, dtype: str

In [415]:
# Filtrage des données sur le produit "Viande de Volailles"
volaille = dispo_clean[dispo_clean["Produit"] == "Viande de Volailles"].copy()

print("Dimensions du sous-ensemble volaille :", volaille.shape)
volaille.head()

Dimensions du sous-ensemble volaille : (2061, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.00,S,Données standardisées

In [ ]:
# Liste des 6 indicateurs retenus pour l'analyse
elements_retenus = [
    "Disponibilité alimentaire (Kcal/personne/jour)",
    "Disponibilité alimentaire en quantité (kg/personne/an)",
    "Importations - Quantité",
    "Production",
    "Exportations - Quantité",
    "Disponibilité intérieure"
]

elements_retenus

['Disponibilité alimentaire (Kcal/personne/jour)',
 'Disponibilité alimentaire en quantité (kg/personne/an)',
 'Importations - Quantité',
 'Production',
 'Exportations - Quantité',
 'Disponibilité intérieure']

In [417]:
# Filtrage sur les 8 indicateurs retenus
volaille_selected = volaille[
    volaille["Élément"].isin(elements_retenus)
].copy()

print("Dimensions après filtrage produit + indicateurs :", volaille_selected.shape)
volaille_selected.head()

Dimensions après filtrage produit + indicateurs : (987, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
658,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/personne/an),2734,Viande de Volailles,2017,2017,kg,1.53,Fc,Donnée calculée
659,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2017,2017,Kcal/personne/jour,5.00,Fc,Donnée calculée

In [418]:
# Vérification du nombre de pays présents dans le sous-ensemble filtré
nb_pays_volaille = volaille_selected["Zone"].nunique()
nb_pays_pop_2017 = population_2017["Zone"].nunique()

print(f"Nombre de pays dans volaille_selected : {nb_pays_volaille}")
print(f"Nombre de pays dans population_2017 : {nb_pays_pop_2017}")

Nombre de pays dans volaille_selected : 172
Nombre de pays dans population_2017 : 236

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧹</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.2 • Filtrage des indicateurs utiles</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Le périmètre de travail a été resserré afin de ne conserver que les données directement utiles à la problématique :
    le produit <b style="color:#FDE68A;">Viande de Volailles</b>, les <b>indicateurs retenus</b> et la population sur l’année <b>2017</b>.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">🍗 Sous-ensemble volaille</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Produit ciblé identifié : <b>Viande de Volailles</b></li>
        <li>Sous-ensemble initial : <b>2 061</b> lignes</li>
        <li>Après filtrage sur les indicateurs retenus : <b>987</b> lignes</li>
        <li>Pays présents : <b>172</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🌍 Population 2017</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Pays / zones présents : <b>236</b></li>
        <li>Année retenue : <b>2017</b></li>
        <li>Unité source : <b>1000 personnes</b></li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Résultat :</b><br>
    Le filtrage a bien recentré l’analyse sur le bon produit et les variables réellement utiles. La base de travail devient
    plus ciblée, plus lisible et plus cohérente pour les étapes suivantes.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Point de vigilance :</b><br>
    Le nombre de pays disponibles dans la population 2017 (<b>236</b>) reste supérieur à celui du sous-ensemble volaille (<b>172</b>).
    Il faudra donc vérifier plus tard quels pays sont réellement exploitables dans les deux sources.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Le filtrage est réussi. À ce stade, rien ne justifie encore d’exclure des pays, mais l’écart de couverture entre les deux
    sources montre déjà qu’un futur filtre qualité sera nécessaire après la fusion.
  </div>
</div>

<a id="etape3_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.3 • Contrôle des types et unités</span>
  </h3>
</div>

In [419]:
# Vérification des types
print("Types de volaille_selected :")
print(volaille_selected.dtypes)

print("\nTypes de population_2017 :")
print(population_2017.dtypes)

Types de volaille_selected :
Code Domaine                  str
Domaine                       str
Code zone                   int64
Zone                          str
Code Élément                int64
Élément                       str
Code Produit                int64
Produit                       str
Code année                  int64
Année                       int64
Unité                         str
Valeur                    float64
Symbole                       str
Description du Symbole        str
dtype: object

Types de population_2017 :
Code Domaine                  str
Domaine                       str
Code zone                   int64
Zone                          str
Code Élément                int64
Élément                       str
Code Produit                int64
Produit                       str
Code année                  int64
Année                       int64
Unité                         str
Valeur                    float64
Symbole                       str
Description du Symbole        str
Note                          str
dtype: object

In [420]:
# Conversion des colonnes Valeur en numérique
volaille_selected["Valeur"] = pd.to_numeric(volaille_selected["Valeur"], errors="coerce")
population_2017["Valeur"] = pd.to_numeric(population_2017["Valeur"], errors="coerce")

# Harmonisation de l'unité population : 1000 personnes -> personnes
population_2017["Valeur"] = population_2017["Valeur"] * 1_000
population_2017["Unité"] = "personnes"

# Harmonisation légère des libellés d'unités
volaille_selected["Unité"] = volaille_selected["Unité"].replace({
    "Kcal/personne/jour": "kcal/personne/jour"
})

print("✅ Colonnes 'Valeur' converties en numérique.")
print("✅ Population 2017 convertie en personnes.")
print("✅ Libellés d'unités harmonisés.")

✅ Colonnes 'Valeur' converties en numérique.
✅ Population 2017 convertie en personnes.
✅ Libellés d'unités harmonisés.

In [421]:
# Vérification des unités présentes dans le sous-ensemble volaille
volaille_selected[["Élément", "Unité"]].drop_duplicates().sort_values(by="Élément")

,Élément,Unité
659,Disponibilité alimentaire (Kcal/personne/jour),kcal/personne/jour
658,Disponibilité alimentaire en quantité (kg/personne/an),kg
654,Disponibilité intérieure,Milliers de tonnes
1707,Exportations - Quantité,Milliers de tonnes
652,Importations - Quantité,Milliers de tonnes
651,Production,Milliers de tonnes

In [422]:
# Vérification des unités présentes dans la population
population_2017[["Élément", "Unité"]].drop_duplicates()

              Élément      Unité
17  Population totale  personnes

In [423]:
# Vérification des années après filtrage
print("Années présentes dans volaille_selected :", volaille_selected["Année"].unique())
print("Années présentes dans population_2017 :", population_2017["Année"].unique())

Années présentes dans volaille_selected : [2017]
Années présentes dans population_2017 : [2017]

In [424]:
# Contrôle rapide de cohérence des valeurs numériques
print("Résumé statistique — volaille_selected")
display(volaille_selected["Valeur"].describe())

print("Résumé statistique — population_2017")
display(population_2017["Valeur"].describe())

Résumé statistique — volaille_selected

count   987.00
mean    291.88
std      1 419
min       0.00
25%       7.00
50%      31.00
75%     111.00
max     21 914
Name: Valeur, dtype: float64

Résumé statistique — population_2017

count            236.00
mean     31.98 millions
std     131.89 millions
min              793.00
25%             380 303
50%       5.20 millions
75%      19.31 millions
max      1.42 milliards
Name: Valeur, dtype: float64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">📏</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.3 • Contrôle des types et unités</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Les types de données, les unités de mesure et le périmètre temporel ont été vérifiés afin de garantir la cohérence technique
    du jeu de données avant la fusion et la création de variables dérivées.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Contrôles validés</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Colonne <b>Valeur</b> convertie en numérique</li>
        <li>Année confirmée : <b>2017</b> dans les deux sous-ensembles</li>
        <li>Population convertie de <b>1000 personnes</b> vers <b>personnes</b></li>
        <li>Unités vérifiées et cohérentes par indicateur</li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">📐 Unités relevées</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Kcal/personne/jour</li>
        <li>kg/personne/an</li>
        <li>Milliers de tonnes</li>
        <li>personnes</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Conclusion :</b><br>
    Les unités observées sont cohérentes avec les indicateurs sélectionnés. Le périmètre temporel est bien aligné sur 2017,
    ce qui rend la comparaison entre les deux sources possible.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Point important :</b><br>
    La cohérence des unités est essentielle avant toute fusion ou construction de variables dérivées. À ce stade,
    rien n’indique d’erreur technique majeure sur les types ou les mesures.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Cette étape est validée. Les données sont techniquement exploitables pour construire un dataset pays, à condition de bien gérer
    ensuite les pays incomplets et les différences de couverture entre sources.
  </div>
</div>

<a id="etape3_4"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.4 • Exclusion des petits territoires atypiques</span>
  </h3>
</div>

In [425]:
# Zones identifiées comme peu pertinentes pour le périmètre d'analyse final
zones_a_exclure = [
    "Maldives",
    "Saint-Vincent-et-les Grenadines",
    "Kiribati",
    "Sainte-Lucie",
    "Nouvelle-Calédonie",
    "Vanuatu",
    "Cabo Verde",
    "Saint-Kitts-et-Nevis"
]

zones_a_exclure

['Maldives',
 'Saint-Vincent-et-les Grenadines',
 'Kiribati',
 'Sainte-Lucie',
 'Nouvelle-Calédonie',
 'Vanuatu',
 'Cabo Verde',
 'Saint-Kitts-et-Nevis']

In [426]:
# Exclusion des petits territoires atypiques dans les deux sous-ensembles
volaille_selected = volaille_selected[
    ~volaille_selected["Zone"].isin(zones_a_exclure)
].copy()

population_2017 = population_2017[
    ~population_2017["Zone"].isin(zones_a_exclure)
].copy()

print("Dimensions volaille_selected après exclusion :", volaille_selected.shape)
print("Dimensions population_2017 après exclusion :", population_2017.shape)

Dimensions volaille_selected après exclusion : (947, 14)
Dimensions population_2017 après exclusion : (228, 15)

In [427]:
# Vérification du nombre de pays restants
print("Nombre de pays dans volaille_selected :", volaille_selected["Zone"].nunique())
print("Nombre de pays dans population_2017 :", population_2017["Zone"].nunique())

Nombre de pays dans volaille_selected : 164
Nombre de pays dans population_2017 : 228

In [428]:
# Contrôle : les zones exclues ne doivent plus apparaître
print("Zones encore présentes dans volaille_selected :")
print(volaille_selected[volaille_selected["Zone"].isin(zones_a_exclure)]["Zone"].unique())

print("\\nZones encore présentes dans population_2017 :")
print(population_2017[population_2017["Zone"].isin(zones_a_exclure)]["Zone"].unique())

Zones encore présentes dans volaille_selected :
<StringArray>
[]
Length: 0, dtype: str
\nZones encore présentes dans population_2017 :
<StringArray>
[]
Length: 0, dtype: str

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🏝️</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.4 • Exclusion des petits territoires atypiques</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Les petits territoires identifiés en amont comme peu représentatifs d’une stratégie d’expansion internationale ont été retirés
    du périmètre de travail. L’objectif est d’éviter qu’un très faible poids démographique ou territorial ne vienne brouiller l’analyse pays.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Résultat sur les sous-ensembles</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>8 zones</b> exclues du périmètre</li>
        <li><b>947 lignes</b> restantes dans <b>volaille_selected</b></li>
        <li><b>228 lignes</b> restantes dans <b>population_2017</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🌍 Pays restants</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>164 pays</b> dans le sous-ensemble volaille</li>
        <li><b>228 pays / zones</b> dans la population 2017</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    📌 <b style="color:#F9A8D4;">Zones exclues :</b><br>
    Maldives, Saint-Vincent-et-les Grenadines, Kiribati, Sainte-Lucie, Nouvelle-Calédonie, Vanuatu, Cabo Verde, Saint-Kitts-et-Nevis.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    🔎 <b style="color:#FDE68A;">Contrôle de cohérence :</b><br>
    Les vérifications confirment que les zones exclues n’apparaissent plus ni dans <b>volaille_selected</b>, ni dans <b>population_2017</b>.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    👉 <b style="color:#86EFAC;">En clair :</b><br>
    Le périmètre d’analyse est maintenant plus homogène et mieux adapté à une étude de ciblage pays.
    La suite du nettoyage et de la construction du dataset se fera sur une base plus robuste et plus pertinente pour le COMEX.
  </div>
</div>

<a id="etape3_5"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.5 • Gestion des valeurs manquantes</span>
  </h3>
</div>

In [429]:
# Valeurs manquantes dans le sous-ensemble volaille_selected
missing_volaille = volaille_selected.isnull().sum().sort_values(ascending=False)
missing_volaille[missing_volaille > 0]

Series([], dtype: int64)

In [430]:
# Valeurs manquantes dans population_2017
missing_pop_2017 = population_2017.isnull().sum().sort_values(ascending=False)
missing_pop_2017[missing_pop_2017 > 0]

Note    227
dtype: int64

In [431]:
# Vérification du nombre d'indicateurs disponibles par pays
# Chaque pays devrait idéalement disposer des 8 indicateurs retenus
nb_indicateurs_par_pays = (
    volaille_selected.groupby("Zone")["Élément"]
    .nunique()
    .sort_values()
)

nb_indicateurs_par_pays.head(20)

Zone
Ouzbékistan                              2
République démocratique populaire lao    2
Djibouti                                 4
Afghanistan                              5
Cambodge                                 5
Gambie                                   5
Bahamas                                  5
Bangladesh                               5
Haïti                                    5
Grenade                                  5
Guinée                                   5
Guinée-Bissau                            5
Mali                                     5
Malawi                                   5
Cuba                                     5
Burkina Faso                             5
Madagascar                               5
Mauritanie                               5
Népal                                    5
Mongolie                                 5
Name: Élément, dtype: int64

In [ ]:
# Pays avec moins de 8 indicateurs disponibles
pays_incomplets = nb_indicateurs_par_pays[nb_indicateurs_par_pays < len(elements_retenus)]
pays_incomplets

Zone
Ouzbékistan                              2
République démocratique populaire lao    2
Djibouti                                 4
Afghanistan                              5
Cambodge                                 5
Gambie                                   5
Bahamas                                  5
Bangladesh                               5
Haïti                                    5
Grenade                                  5
Guinée                                   5
Guinée-Bissau                            5
Mali                                     5
Malawi                                   5
Cuba                                     5
Burkina Faso                             5
Madagascar                               5
Mauritanie                               5
Népal                                    5
Mongolie                                 5
République centrafricaine                5
Mozambique                               5
Sao Tomé-et-Principe                     5
République-Unie de Tanzanie              5
Éthiopie                                 5
Timor-Leste                              5
Zimbabwe                                 5
Turkménistan                             5
Tadjikistan                              5
Soudan                                   5
Name: Élément, dtype: int64

In [ ]:
# Vérification de la disponibilité de la population 2017 par pays
population_2017["Zone"].nunique(), population_2017.shape

(228, (228, 15))

In [ ]:
# Première liste de pays potentiellement fragiles
# (à surveiller)
print("Nombre de pays avec moins de 8 indicateurs :", pays_incomplets.shape[0])

Nombre de pays avec moins de 8 indicateurs : 30

In [ ]:
# On garde pour l'instant le maximum d'information
# mais on crée une liste de pays complets pour la suite
pays_complets = nb_indicateurs_par_pays[
    nb_indicateurs_par_pays == len(elements_retenus)
].index.tolist()

print("Nombre de pays complets sur les 8 indicateurs :", len(pays_complets))

Nombre de pays complets sur les 8 indicateurs : 134

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧩</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.5 • Gestion des valeurs manquantes</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Les valeurs manquantes ont été contrôlées après harmonisation des types, des unités et exclusion des petits territoires atypiques.
    L’objectif est désormais d’identifier les pays dont l’information reste incomplète avant la construction du dataset final.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Points rassurants</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>0 valeur manquante utile</b> dans <b>volaille_selected</b></li>
        <li>La colonne <b>Note</b> de la population contient des NA, mais elle n’est pas utilisée</li>
        <li><b>134 pays</b> disposent de tous les indicateurs retenus</li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(250,204,21,0.08);
      border:1px solid rgba(250,204,21,0.28);
    ">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">⚠️ Points à surveiller</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>30 pays</b> ont moins de tous les indicateurs disponibles</li>
        <li>Certains pays n’ont que <b>2, 4 ou 5 indicateurs</b></li>
        <li>Ces cas devront être réévalués avant la fusion finale</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    📍 <b style="color:#F9A8D4;">Lecture métier :</b><br>
    Les données volaille sont globalement propres, ce qui est très positif. Le principal enjeu ne vient pas des valeurs manquantes brutes,
    mais d’une <b>complétude inégale selon les pays</b>.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(56,189,248,0.08);
    border:1px solid rgba(56,189,248,0.28);
  ">
    👉 <b style="color:#BFE9FF;">Décision à ce stade :</b><br>
    Il n’est pas nécessaire de supprimer immédiatement ces 30 pays. En revanche, ils doivent être conservés comme <b>pays incomplets à surveiller</b>,
    car ils pourront soit être exclus plus tard, soit être traités séparément selon le niveau final de qualité exigé pour l’ACP et le clustering.
  </div>
</div>

<a id="etape3_6"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.6 • Traitement des doublons</span>
  </h3>
</div>

In [ ]:
# Vérification des doublons exacts dans le sous-ensemble volaille_selected
duplicated_volaille = volaille_selected.duplicated().sum()
print("Nombre de doublons exacts dans volaille_selected :", duplicated_volaille)

Nombre de doublons exacts dans volaille_selected : 0

In [ ]:
# Vérification des doublons exacts dans population_2017
duplicated_population = population_2017.duplicated().sum()
print("Nombre de doublons exacts dans population_2017 :", duplicated_population)

Nombre de doublons exacts dans population_2017 : 0

In [ ]:
# Vérification de doublons logiques sur les clés métier
# Un pays ne devrait apparaître qu'une fois par indicateur dans volaille_selected
doublons_logiques_volaille = volaille_selected.duplicated(
    subset=["Zone", "Élément"]
).sum()

print("Nombre de doublons logiques (Zone + Élément) dans volaille_selected :", doublons_logiques_volaille)

Nombre de doublons logiques (Zone + Élément) dans volaille_selected : 0

In [ ]:
# Pour la population 2017, un pays devrait apparaître une seule fois
doublons_logiques_population = population_2017.duplicated(
    subset=["Zone"]
).sum()

print("Nombre de doublons logiques (Zone) dans population_2017 :", doublons_logiques_population)

Nombre de doublons logiques (Zone) dans population_2017 : 0

In [ ]:
# Suppression des doublons exacts si nécessaire
volaille_selected = volaille_selected.drop_duplicates().copy()
population_2017 = population_2017.drop_duplicates().copy()

print("✅ Doublons exacts supprimés si nécessaire.")
print("Nouvelles dimensions volaille_selected :", volaille_selected.shape)
print("Nouvelles dimensions population_2017 :", population_2017.shape)

✅ Doublons exacts supprimés si nécessaire.
Nouvelles dimensions volaille_selected : (947, 14)
Nouvelles dimensions population_2017 : (228, 15)

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧾</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.6 • Traitement des doublons</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Les doublons exacts et les doublons logiques ont été contrôlés afin de vérifier qu’un même pays ne soit pas représenté plusieurs fois
    pour une même information. Cette étape permet de sécuriser la fiabilité du futur dataset pays.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">🍗 Sous-ensemble volaille</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Doublons exacts : <b>0</b></li>
        <li>Doublons logiques (Zone + Élément) : <b>0</b></li>
        <li>Dimensions après contrôle : <b>947 lignes</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🌍 Population 2017</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Doublons exacts : <b>0</b></li>
        <li>Doublons logiques (Zone) : <b>0</b></li>
        <li>Dimensions après contrôle : <b>228 lignes</b></li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Conclusion :</b><br>
    Aucune anomalie de duplication n’a été détectée, ni dans les doublons exacts, ni dans les doublons logiques.
    Les deux sous-ensembles sont donc cohérents sur ce point.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Lecture métier :</b><br>
    C’est un très bon signal qualité : chaque pays apparaît une seule fois par indicateur dans le sous-ensemble volaille,
    et une seule fois dans le fichier population 2017. Le dataset est donc prêt à être fusionné sans risque de duplication artificielle.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    La base de travail est propre sur la question des doublons. La suite pourra donc se concentrer sur la fusion,
    la construction du dataset final et les vérifications de cohérence business.
  </div>
</div>

<a id="etape4"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(52,211,153,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(6,74,53,0.96), rgba(5,37,27,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(78%) sepia(32%) saturate(1109%) hue-rotate(113deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span style="color:#FFFFFF;">🔗 Étape 4</span>
    <span>• Construction du dataset d’analyse</span>
  </h2>
</div>

<a id="etape4_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(134,239,172,0.28);
  border-radius:12px;
  background:rgba(134,239,172,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(89%) sepia(17%) saturate(874%) hue-rotate(88deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span>4.1 • Intégration de la population</span>
  </h3>
</div>

In [ ]:
# Préparation du fichier population pour la fusion
population_2017_simple = population_2017[["Zone", "Valeur"]].copy()
population_2017_simple = population_2017_simple.rename(columns={"Valeur": "population_2017"})

print("Dimensions population_2017_simple :", population_2017_simple.shape)
population_2017_simple.head()

Dimensions population_2017_simple : (228, 2)

              Zone  population_2017
17     Afghanistan   36.30 millions
36  Afrique du Sud   57.01 millions
55         Albanie    2.88 millions
74         Algérie   41.39 millions
93       Allemagne   82.66 millions

In [ ]:
# Vérification qu'il y a bien une seule ligne par pays
print("Pays uniques dans df_pivot_fao :", df_pivot_fao["Zone"].nunique())
print("Lignes dans df_pivot_fao :", df_pivot_fao.shape[0])

print("Pays uniques dans population_2017_simple :", population_2017_simple["Zone"].nunique())
print("Lignes dans population_2017_simple :", population_2017_simple.shape[0])

Pays uniques dans df_pivot_fao : 172
Lignes dans df_pivot_fao : 172
Pays uniques dans population_2017_simple : 228
Lignes dans population_2017_simple : 228

In [ ]:
# Fusion du dataset FAO pivoté avec la population
df_analyse = df_pivot_fao.merge(
    population_2017_simple,
    on="Zone",
    how="left"
)

print("Dimensions après fusion avec la population :", df_analyse.shape)
df_analyse.head()

Dimensions après fusion avec la population : (172, 10)

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production,population_2017
0,Afghanistan,5.00,1.53,0.33,0.54,57.00,NaN,29.00,28.00,36.30 millions
1,Afrique du Sud,143.00,35.69,9.25,14.11,2 118,63.00,514.00,1 667,57.01 millions
2,Albanie,85.00,16.36,6.45,6.26,47.00,0.00,38.00,13.00,2.88 millions
3,Algérie,22.00,6.38,1.50,1.97,277.00,0.00,2.00,275.00,41.39 millions
4,Allemagne,71.00,19.47,4.16,7.96,1 739,646.00,842.00,1 514,82.66 millions

In [ ]:
# Contrôle des valeurs manquantes après ajout de la population
missing_after_population = df_analyse.isnull().sum().sort_values(ascending=False)
missing_after_population[missing_after_population > 0]

Exportations - Quantité     37
population_2017              8
Production                   4
Disponibilité intérieure     2
Importations - Quantité      2
dtype: int64

In [ ]:
# Identification des pays sans population après fusion
pays_sans_population = df_analyse[df_analyse["population_2017"].isnull()]["Zone"].tolist()

print("Nombre de pays sans population :", len(pays_sans_population))
pays_sans_population[:20]

Nombre de pays sans population : 8

['Cabo Verde',
 'Kiribati',
 'Maldives',
 'Nouvelle-Calédonie',
 'Saint-Kitts-et-Nevis',
 'Saint-Vincent-et-les Grenadines',
 'Sainte-Lucie',
 'Vanuatu']

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(6,78,59,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(74,222,128,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🌍</span>
    <b style="font-size:19px; color:#86EFAC;">Étape 4.1 • Intégration de la population</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Le dataset pivoté a ensuite été <b>fusionné avec la population 2017</b> afin d’ajouter une variable démographique essentielle à l’analyse du marché.
    Cette variable permet de contextualiser les volumes observés par pays.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">📦 Résultat de la fusion</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>172 lignes</b> dans le dataset après fusion</li>
        <li><b>10 colonnes</b> au total</li>
        <li>Ajout de la variable <b>population_2017</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Contrôles de cohérence</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>172 pays uniques</b> dans le pivot FAO</li>
        <li><b>228 pays uniques</b> dans la population 2017</li>
        <li><b>8 pays sans population</b> après fusion</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Lecture des résultats :</b><br>
    La fusion avec la population est globalement réussie, mais quelques zones restent sans correspondance démographique
    (<b>8 pays</b>, principalement de petits territoires comme Cabo Verde, Kiribati, Maldives, Nouvelle-Calédonie, Saint-Kitts-et-Nevis, Saint-Vincent-et-les-Grenadines, Sainte-Lucie et Vanuatu).
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(248,113,113,0.08);
    border:1px solid rgba(248,113,113,0.26);
  ">
    ⚠️ <b style="color:#FCA5A5;">Point de vigilance conservé :</b><br>
    Les valeurs manquantes restantes ne concernent pas uniquement la population, mais aussi certains indicateurs FAO déjà repérés
    après pivot : <b>Exportations - Quantité (37)</b>, <b>Production (4)</b>, <b>Disponibilité intérieure (2)</b> et
    <b>Importations - Quantité (2)</b>.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    👉 <b style="color:#86EFAC;">En clair :</b><br>
    Le dataset d’analyse est maintenant enrichi d’une variable démographique structurante. La base est plus complète,
    mais un filtre qualité restera nécessaire plus loin pour exclure les pays encore incomplets.
  </div>
</div>

<a id="etape4_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(134,239,172,0.28);
  border-radius:12px;
  background:rgba(134,239,172,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(89%) sepia(17%) saturate(874%) hue-rotate(88deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span>4.2 • Ajout d’éventuelles sources externes</span>
  </h3>
</div>

In [ ]:
# Vérification des sources actuellement disponibles dans le projet
sources_disponibles = [
    "DisponibiliteAlimentaire_2017.csv",
    "Population_2000_2018.csv"
]

print("Sources actuellement disponibles :")
for source in sources_disponibles:
    print("-", source)

print("\nVariables externes demandées mais non présentes dans les fichiers actuels :")
print("- PIB")
print("- Stabilité politique")

Sources actuellement disponibles :
- DisponibiliteAlimentaire_2017.csv
- Population_2000_2018.csv

Variables externes demandées mais non présentes dans les fichiers actuels :
- PIB
- Stabilité politique

In [ ]:
# Import du fichier des sources externes préparé en amont
sources_externes_2017 = pd.read_csv(
    "data/sources_externes_2017.csv",
    sep=",",
    encoding="utf-8-sig"
)

print("✅ Fichier sources_externes_2017 chargé.")
print("Dimensions :", sources_externes_2017.shape)
display(sources_externes_2017.head())

✅ Fichier sources_externes_2017 chargé.
Dimensions : (164, 3)

             Zone          PIB_2017  stabilite_politique_2017
0     Afghanistan   18.75 milliards                     -2.79
1  Afrique du Sud  381.45 milliards                     -0.28
2         Albanie   13.26 milliards                      0.37
3         Algérie  189.88 milliards                     -0.92
4       Allemagne 3765.35 milliards                      0.57

In [ ]:
# Vérification des colonnes disponibles
print("Colonnes du fichier sources externes :")
print(sources_externes_2017.columns.tolist())

Colonnes du fichier sources externes :
['Zone', 'PIB_2017', 'stabilite_politique_2017']

In [ ]:
# Vérification des types
print("Types des colonnes :")
print(sources_externes_2017.dtypes)

Types des colonnes :
Zone                            str
PIB_2017                    float64
stabilite_politique_2017    float64
dtype: object

In [ ]:
# Vérification de l'unicité des zones
print("Nombre de zones uniques :", sources_externes_2017["Zone"].nunique())
print("Nombre total de lignes :", sources_externes_2017.shape[0])

Nombre de zones uniques : 164
Nombre total de lignes : 164

In [ ]:
# Vérification des doublons potentiels
doublons_sources_externes = sources_externes_2017.duplicated(subset=["Zone"]).sum()
print("Nombre de doublons logiques sur Zone :", doublons_sources_externes)

Nombre de doublons logiques sur Zone : 0

In [ ]:
# Vérification des valeurs manquantes
missing_sources_externes = sources_externes_2017.isnull().sum().sort_values(ascending=False)
missing_sources_externes[missing_sources_externes > 0]

stabilite_politique_2017    4
PIB_2017                    2
dtype: int64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(6,78,59,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(74,222,128,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧪</span>
    <b style="font-size:19px; color:#86EFAC;">Étape 4.2 • Ajout d’éventuelles sources externes</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Les variables externes demandées, absentes des fichiers FAO initiaux, ont été préparées puis chargées dans un fichier dédié :
    <b>sources_externes_2017.csv</b>. Ce fichier regroupe les informations de <b>PIB 2017</b> et de <b>stabilité politique 2017</b>.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">📁 Fichier chargé</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>164 lignes</b></li>
        <li><b>3 colonnes</b></li>
        <li><b>Zone</b>, <b>PIB_2017</b>, <b>stabilite_politique_2017</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Contrôles réalisés</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>164 zones uniques</b></li>
        <li><b>0 doublon logique</b> sur la clé Zone</li>
        <li>Types corrects : Zone en texte, variables externes en numérique</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Valeurs manquantes observées :</b><br>
    Le fichier externe reste globalement propre, mais quelques valeurs sont absentes :
    <b>PIB_2017 : 2</b> et <b>stabilite_politique_2017 : 4</b>.
    Les zones ciblées pour vérification montrent par exemple des absences sur
    <b>Chine, Taiwan Province de</b>, <b>République populaire démocratique de Corée</b> ou encore
    <b>Polynésie française</b> pour la stabilité politique.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    👉 <b style="color:#86EFAC;">En clair :</b><br>
    La source externe 2017 est suffisamment propre pour être fusionnée avec la base d’analyse. Les quelques valeurs manquantes
    restantes sont identifiées et pourront être prises en compte lors du filtrage final du périmètre.
  </div>
</div>

<a id="etape4_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(134,239,172,0.28);
  border-radius:12px;
  background:rgba(134,239,172,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(89%) sepia(17%) saturate(874%) hue-rotate(88deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span>4.3 • Création du dataset final enrichi</span>
  </h3>
</div>

In [ ]:
# Base propre avant enrichissement externe
df_analyse_clean = df_analyse[[
    "Zone",
    "Disponibilité alimentaire (Kcal/personne/jour)",
    "Disponibilité alimentaire en quantité (kg/personne/an)",
    "Disponibilité intérieure",
    "Exportations - Quantité",
    "Importations - Quantité",
    "Production",
    "population_2017"
]].copy()

print("✅ Base propre recréée.")
print("Dimensions :", df_analyse_clean.shape)
display(df_analyse_clean.head())

✅ Base propre recréée.
Dimensions : (172, 8)

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production,population_2017
0,Afghanistan,5.00,1.53,57.00,NaN,29.00,28.00,36.30 millions
1,Afrique du Sud,143.00,35.69,2 118,63.00,514.00,1 667,57.01 millions
2,Albanie,85.00,16.36,47.00,0.00,38.00,13.00,2.88 millions
3,Algérie,22.00,6.38,277.00,0.00,2.00,275.00,41.39 millions
4,Allemagne,71.00,19.47,1 739,646.00,842.00,1 514,82.66 millions

In [ ]:
# Fusion propre du dataset d'analyse avec les sources externes
dataset_final = df_analyse_clean.merge(
    sources_externes_2017,
    on="Zone",
    how="left"
)

print("✅ Dataset final enrichi créé.")
print("Dimensions :", dataset_final.shape)
display(dataset_final.head())

✅ Dataset final enrichi créé.
Dimensions : (172, 10)

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production,population_2017,PIB_2017,stabilite_politique_2017
0,Afghanistan,5.00,1.53,57.00,NaN,29.00,28.00,36.30 millions,18.75 milliards,-2.79
1,Afrique du Sud,143.00,35.69,2 118,63.00,514.00,1 667,57.01 millions,381.45 milliards,-0.28
2,Albanie,85.00,16.36,47.00,0.00,38.00,13.00,2.88 millions,13.26 milliards,0.37
3,Algérie,22.00,6.38,277.00,0.00,2.00,275.00,41.39 millions,189.88 milliards,-0.92
4,Allemagne,71.00,19.47,1 739,646.00,842.00,1 514,82.66 millions,3765.35 milliards,0.57

In [ ]:
print("Colonnes du dataset final :")
print(dataset_final.columns.tolist())

Colonnes du dataset final :
['Zone', 'Disponibilité alimentaire (Kcal/personne/jour)', 'Disponibilité alimentaire en quantité (kg/personne/an)', 'Disponibilité intérieure', 'Exportations - Quantité', 'Importations - Quantité', 'Production', 'population_2017', 'PIB_2017', 'stabilite_politique_2017']

In [ ]:
print("Types du dataset final :")
print(dataset_final.dtypes)

Types du dataset final :
Zone                                                          str
Disponibilité alimentaire (Kcal/personne/jour)            float64
Disponibilité alimentaire en quantité (kg/personne/an)    float64
Disponibilité intérieure                                  float64
Exportations - Quantité                                   float64
Importations - Quantité                                   float64
Production                                                float64
population_2017                                           float64
PIB_2017                                                  float64
stabilite_politique_2017                                  float64
dtype: object

In [ ]:
print("Nombre de pays uniques dans le dataset final :", dataset_final["Zone"].nunique())
print("Nombre total de lignes :", dataset_final.shape[0])

Nombre de pays uniques dans le dataset final : 172
Nombre total de lignes : 172

In [ ]:
print("Pays sans PIB :")
display(
    dataset_final.loc[dataset_final["PIB_2017"].isnull(), ["Zone"]]
    .drop_duplicates()
    .sort_values("Zone")
)

print("Pays sans stabilité politique :")
display(
    dataset_final.loc[dataset_final["stabilite_politique_2017"].isnull(), ["Zone"]]
    .drop_duplicates()
    .sort_values("Zone")
)

Pays sans PIB :

                                           Zone
26                                   Cabo Verde
33                    Chine, Taiwan Province de
80                                     Kiribati
92                                     Maldives
108                          Nouvelle-Calédonie
131  République populaire démocratique de Corée
133                        Saint-Kitts-et-Nevis
134             Saint-Vincent-et-les Grenadines
135                                Sainte-Lucie
160                                     Vanuatu

Pays sans stabilité politique :

                                Zone
26                        Cabo Verde
31          Chine - RAS de Hong-Kong
32              Chine - RAS de Macao
33         Chine, Taiwan Province de
80                          Kiribati
92                          Maldives
108               Nouvelle-Calédonie
120              Polynésie française
133             Saint-Kitts-et-Nevis
134  Saint-Vincent-et-les Grenadines
135                     Sainte-Lucie
160                          Vanuatu

In [ ]:
zones_a_verifier = [
    "Bulgarie",
    "Chine - RAS de Hong-Kong",
    "Chine - RAS de Macao",
    "Chine, Taiwan Province de",
    "Chypre",
    "Danemark",
    "Guinée-Bissau",
    "Géorgie",
    "Malte",
    "Pérou",
    "Polynésie française",
    "République populaire démocratique de Corée",
    "Serbie",
    "Tadjikistan"
]

sources_externes_2017[
    sources_externes_2017["Zone"].isin(zones_a_verifier)
].sort_values("Zone")

,Zone,PIB_2017,stabilite_politique_2017
22,Bulgarie,59.17 milliards,0.32
30,Chine - RAS de Hong-Kong,341.27 milliards,NaN
31,Chine - RAS de Macao,50.30 milliards,NaN
32,"Chine, Taiwan Province de",NaN,NaN
34,Chypre,22.95 milliards,0.53
41,Danemark,331.61 milliards,0.85
59,Guinée-Bissau,1.47 milliards,-0.50
61,Géorgie,16.47 milliards,-0.38
91,Malte,14.16 milliards,1.24
116,Polynésie française,5.83 milliards,NaN
118,Pérou,211.01 milliards,-0.26
127,République populaire démocratique de Corée,NaN,-0.50
131,Serbie,45.97 milliards,0.08
141,Tadjikistan,7.54 milliards,-0.67

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(6,78,59,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(74,222,128,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧩</span>
    <b style="font-size:19px; color:#86EFAC;">Étape 4.3 • Création du dataset final enrichi</b>
  </div>

  <p style="margin:0 0 12px 0;">
    La base d’analyse a été enrichie par fusion avec les <b>sources externes 2017</b>, afin d’ajouter deux variables contextuelles :
    le <b>PIB 2017</b> et la <b>stabilité politique 2017</b>. Cette étape permet d’obtenir une vision plus complète des pays étudiés.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">📦 Structure du dataset enrichi</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>172 pays</b> dans le dataset enrichi</li>
        <li><b>10 colonnes</b> au total</li>
        <li>Ajout de <b>PIB_2017</b> et <b>stabilite_politique_2017</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🌍 Variables externes intégrées</div>
      <ul style="margin:0; padding-left:18px;">
        <li>PIB 2017</li>
        <li>Stabilité politique 2017</li>
        <li>Fusion réalisée sur la clé <b>Zone</b></li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    ⚠️ <b style="color:#FDE68A;">Point de vigilance :</b><br>
    Après enrichissement, certaines valeurs manquent encore sur les variables externes :
    <b>PIB_2017 (10)</b> et <b>stabilite_politique_2017 (12)</b>, ainsi que quelques valeurs manquantes résiduelles
    dans certaines variables FAO (<b>Exportations - Quantité : 37</b>, <b>Production : 4</b>, <b>Importations - Quantité : 2</b>,
    <b>Disponibilité intérieure : 2</b>, <b>population_2017 : 8</b>).
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">En clair :</b><br>
    Le dataset final enrichi est correctement construit. Il contient l’ensemble des variables métier et des variables externes
    utiles à l’analyse, avant application du filtre qualité final sur les pays incomplets.
  </div>
</div>

<a id="etape4_4"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(134,239,172,0.28);
  border-radius:12px;
  background:rgba(134,239,172,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(89%) sepia(17%) saturate(874%) hue-rotate(88deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span>4.4 • Vérification du périmètre final (100 pays minimum)</span>
  </h3>
</div>

In [ ]:
# Valeurs manquantes avant filtrage final
print("Valeurs manquantes par colonne :")
display(dataset_final.isnull().sum()[dataset_final.isnull().sum() > 0])

Valeurs manquantes par colonne :

Disponibilité intérieure     2
Exportations - Quantité     37
Importations - Quantité      2
Production                   4
population_2017              8
PIB_2017                    10
stabilite_politique_2017    12
dtype: int64

In [ ]:
# Création du dataset final exploitable
dataset_final_complet = dataset_final.dropna().copy()

print("Dimensions du dataset final complet :", dataset_final_complet.shape)
print("Nombre de pays conservés :", dataset_final_complet["Zone"].nunique())

display(dataset_final_complet.head())

Dimensions du dataset final complet : (129, 10)
Nombre de pays conservés : 129

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production,population_2017,PIB_2017,stabilite_politique_2017
1,Afrique du Sud,143.00,35.69,2 118,63.00,514.00,1 667,57.01 millions,381.45 milliards,-0.28
2,Albanie,85.00,16.36,47.00,0.00,38.00,13.00,2.88 millions,13.26 milliards,0.37
3,Algérie,22.00,6.38,277.00,0.00,2.00,275.00,41.39 millions,189.88 milliards,-0.92
4,Allemagne,71.00,19.47,1 739,646.00,842.00,1 514,82.66 millions,3765.35 milliards,0.57
5,Angola,35.00,10.56,319.00,0.00,277.00,42.00,29.82 millions,84.38 milliards,-0.39

In [ ]:
# Vérification du périmètre final
nb_pays_final = dataset_final["Zone"].nunique()

print("Nombre final de pays :", nb_pays_final)

if nb_pays_final >= 100:
    print("✅ Le périmètre final respecte l'exigence minimale de 100 pays.")
else:
    print("❌ Le périmètre final ne respecte pas l'exigence minimale de 100 pays.")

Nombre final de pays : 172
✅ Le périmètre final respecte l'exigence minimale de 100 pays.

In [ ]:
# Pays exclus car incomplets
pays_exclus = sorted(set(dataset_final["Zone"]) - set(dataset_final_complet["Zone"]))

print("Nombre de pays exclus :", len(pays_exclus))
pays_exclus

Nombre de pays exclus : 43

['Afghanistan',
 'Bahamas',
 'Bangladesh',
 'Burkina Faso',
 'Cabo Verde',
 'Cambodge',
 'Chine - RAS de Hong-Kong',
 'Chine - RAS de Macao',
 'Chine, Taiwan Province de',
 'Cuba',
 'Djibouti',
 'Gambie',
 'Grenade',
 'Guinée',
 'Guinée-Bissau',
 'Haïti',
 'Kiribati',
 'Madagascar',
 'Malawi',
 'Maldives',
 'Mali',
 'Mauritanie',
 'Mongolie',
 'Mozambique',
 'Nouvelle-Calédonie',
 'Népal',
 'Ouzbékistan',
 'Polynésie française',
 'République centrafricaine',
 'République démocratique populaire lao',
 'République populaire démocratique de Corée',
 'République-Unie de Tanzanie',
 'Saint-Kitts-et-Nevis',
 'Saint-Vincent-et-les Grenadines',
 'Sainte-Lucie',
 'Sao Tomé-et-Principe',
 'Soudan',
 'Tadjikistan',
 'Timor-Leste',
 'Turkménistan',
 'Vanuatu',
 'Zimbabwe',
 'Éthiopie']

In [ ]:
dataset_final = dataset_final_complet.copy()

print("Dimensions finales du dataset :", dataset_final.shape)
print("Nombre final de pays :", dataset_final['Zone'].nunique())
display(dataset_final.head(10))

Dimensions finales du dataset : (129, 10)
Nombre final de pays : 129

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Production,population_2017,PIB_2017,stabilite_politique_2017
1,Afrique du Sud,143.00,35.69,2 118,63.00,514.00,1 667,57.01 millions,381.45 milliards,-0.28
2,Albanie,85.00,16.36,47.00,0.00,38.00,13.00,2.88 millions,13.26 milliards,0.37
3,Algérie,22.00,6.38,277.00,0.00,2.00,275.00,41.39 millions,189.88 milliards,-0.92
4,Allemagne,71.00,19.47,1 739,646.00,842.00,1 514,82.66 millions,3765.35 milliards,0.57
5,Angola,35.00,10.56,319.00,0.00,277.00,42.00,29.82 millions,84.38 milliards,-0.39
6,Antigua-et-Barbuda,233.00,54.10,7.00,0.00,7.00,0.00,95 426,1.53 milliards,0.73
7,Arabie saoudite,151.00,43.36,1 435,10.00,722.00,616.00,33.10 millions,741.27 milliards,-0.65
8,Argentine,182.00,42.24,1 962,207.00,8.00,2 161,43.94 millions,643.63 milliards,0.16
9,Arménie,54.00,16.06,47.00,0.00,35.00,11.00,2.94 millions,11.53 milliards,-0.63
10,Australie,192.00,47.65,1 171,42.00,16.00,1 269,24.58 millions,1330.89 milliards,0.88

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(6,78,59,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(74,222,128,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">✅</span>
    <b style="font-size:19px; color:#86EFAC;">Étape 4.4 • Vérification du périmètre final (100 pays minimum)</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Un filtrage final a été appliqué afin de conserver uniquement les pays disposant d’un ensemble de données complet sur toutes
    les variables retenues. L’objectif est de garantir un dataset final robuste, cohérent et exploitable pour les analyses multivariées.
  </p>

  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">📊 Résultat du filtrage final</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>129 pays</b> conservés dans le dataset final complet</li>
        <li><b>10 colonnes</b> conservées</li>
        <li>Le seuil minimal de <b>100 pays</b> est respecté</li>
      </ul>
    </div>
    <div style="
      padding:12px 6px;
      border-radius:12px;
      background:rgba(236,72,153,0.08);
      border:1px solid rgba(236,72,153,0.26);
    ">
      <div style="font-weight:700; color:#F9A8D4; margin-bottom:6px;">🗑️ Pays exclus car incomplets</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>43 pays</b> exclus après suppression des lignes incomplètes</li>
        <li>Exemples : Afghanistan, Bangladesh, Cabo Verde, Chine - RAS de Hong-Kong, Maldives…</li>
        <li>Exclusion liée à la présence de <b>valeurs manquantes</b></li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Lecture métier :</b><br>
    Le périmètre final est plus restreint que le dataset enrichi initial (<b>172 pays</b>), mais il gagne fortement en qualité.
    Les <b>129 pays restants</b> constituent une base plus fiable pour les analyses statistiques, l’ACP et le clustering.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Conclusion :</b><br>
    Le périmètre final respecte bien l’exigence minimale de <b>100 pays</b>. Le dataset est désormais ramené à une version
    <b>complète et cohérente</b>, prête pour les analyses finales.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(56,189,248,0.08);
    border:1px solid rgba(56,189,248,0.28);
  ">
    👉 <b style="color:#BFE9FF;">En clair :</b><br>
    Le filtre qualité final a bien joué son rôle : il réduit le volume, mais améliore la solidité du dataset.
    La base finale de <b>129 pays</b> est donc celle à utiliser pour la suite.
  </div>
</div>

<a id="etape5"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(244,114,182,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(92,8,54,0.96), rgba(48,7,29,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(79%) sepia(23%) saturate(1712%) hue-rotate(291deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span style="color:#FFFFFF;">🛠️ Étape 5 • Feature engineering</span>
  </h2>
</div>

<a id="etape5_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(249,168,212,0.28);
  border-radius:12px;
  background:rgba(249,168,212,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(18%) saturate(832%) hue-rotate(281deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>5.1 • Création des variables dérivées</span>
  </h3>
</div>

<a id="etape5_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(249,168,212,0.28);
  border-radius:12px;
  background:rgba(249,168,212,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(18%) saturate(832%) hue-rotate(281deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>5.2 • Contrôle de cohérence des nouvelles variables</span>
  </h3>
</div>

<a id="etape5_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(249,168,212,0.28);
  border-radius:12px;
  background:rgba(249,168,212,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(18%) saturate(832%) hue-rotate(281deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>5.3 • Dataset final prêt pour l’ACP</span>
  </h3>
</div>

<a id="etape6"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(250,204,21,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(88,64,5,0.96), rgba(44,31,4,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(84%) sepia(49%) saturate(1328%) hue-rotate(346deg) brightness(103%) contrast(101%);
      ">
    </a>
    <span style="color:#FFFFFF;">🔎 Étape 6 • Analyse exploratoire des données</span>
  </h2>
</div>

<a id="etape6_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,230,138,0.28);
  border-radius:12px;
  background:rgba(253,230,138,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(92%) sepia(19%) saturate(938%) hue-rotate(335deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>6.1 • Statistiques descriptives</span>
  </h3>
</div>

<a id="etape6_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,230,138,0.28);
  border-radius:12px;
  background:rgba(253,230,138,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(92%) sepia(19%) saturate(938%) hue-rotate(335deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>6.2 • Distribution des variables</span>
  </h3>
</div>

<a id="etape6_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,230,138,0.28);
  border-radius:12px;
  background:rgba(253,230,138,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(92%) sepia(19%) saturate(938%) hue-rotate(335deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>6.3 • Détection des outliers</span>
  </h3>
</div>

<a id="etape6_4"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,230,138,0.28);
  border-radius:12px;
  background:rgba(253,230,138,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(92%) sepia(19%) saturate(938%) hue-rotate(335deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>6.4 • Première lecture business des profils pays</span>
  </h3>
</div>

<a id="conclusion1"></a>
<div style="
  width:78%;
  margin:18px auto 14px auto;
  border:1px solid rgba(34,211,238,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(5,72,86,0.96), rgba(4,34,42,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(82%) sepia(22%) saturate(1433%) hue-rotate(148deg) brightness(104%) contrast(102%);
      ">
    </a>
    <span style="color:#FFFFFF;">✅ Conclusion • Synthèse du notebook 1</span>
  </h2>
</div>