<div style="
    display:flex;
    justify-content:center;
    align-items:center;
    width:78%;
    margin:40px auto;
    border-radius:14px;
    background: linear-gradient(45deg, #8a2be2, #ff3cac, #2bd2ff, #8a2be2);
    background-size: 300% 300%;
    animation: borderFlow 7s linear infinite;
    padding:2px;
    box-sizing:border-box;
">
  <div style="
      display:flex;
      align-items:center;
      justify-content:center;
      flex-wrap:wrap;
      gap:22px;
      background: linear-gradient(90deg, rgba(18,18,28,0.96), rgba(28,18,40,0.96));
      color: white;
      font-family: 'Segoe UI', Arial, sans-serif;
      font-size: 25px;
      font-weight: 650;
      letter-spacing: 1px;
      padding: 20px 34px;
      border-radius: 12px;
      width: 100%;
      height: 100%;
      box-sizing:border-box;
  ">
    <img src="assets/img/logo.png"
         alt="Logo La poule qui chante"
         style="height:120px; width:auto; filter: drop-shadow(0 0 10px rgba(255,195,90,0.30));">
    <div style="text-align:center;">
      <div style="font-size:30px; font-weight:700; letter-spacing:1px;">
        La poule qui chante
      </div>
      <span style="font-size:22px; opacity:0.95;">
        Préparation, nettoyage et analyse exploratoire des données
      </span><br>
      <span style="font-size:16px; opacity:0.78; letter-spacing:0.4px;">
        International market screening for poultry export strategy
      </span>
    </div>
  </div>
</div>

<style>
@keyframes borderFlow {
  0% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
}
</style>

# 🎯 Objectif du projet • La poule qui chante 🐔

Ce notebook a pour objectif de **préparer, nettoyer et structurer un jeu de données international** permettant d’identifier des **groupes de pays à cibler pour l’exportation de poulets** par l’entreprise fictive **La poule qui chante**.

L’enjeu est de construire une base d’analyse fiable, exploitable et cohérente, à partir de données issues principalement de la **FAO**, enrichies si nécessaire par d’autres sources open data.

---

## 🧩 Contexte

La direction de **La poule qui chante** souhaite initier une stratégie d’**expansion à l’international**.  
Dans un premier temps, elle ne demande pas une étude de marché pays par pays, mais une **analyse macro** permettant de :

- comparer les pays sur des critères alimentaires, démographiques et économiques ;
- identifier des **groupes homogènes de pays** ;
- faire émerger des **priorités de ciblage** pour de futures analyses marché plus détaillées.

L’analyse devra ensuite être présentée au **COMEX** dans un format clair, synthétique et accessible à un public non technique.

---

## 📌 Objectifs de ce notebook

Ce premier notebook vise à :

- importer et comprendre les données FAO mises à disposition ;
- sélectionner des **variables pertinentes** pour la problématique d’exportation ;
- enrichir l’analyse par une réflexion **PESTEL** ;
- nettoyer, transformer et fusionner les données ;
- construire un **dataset final complet**, sans valeurs manquantes sur les pays retenus ;
- créer des **variables dérivées** utiles à la future segmentation ;
- réaliser une **analyse exploratoire** afin de mieux comprendre la structure des données avant l’ACP et le clustering.

---

## 🧠 Finalité

Ce notebook constitue le socle méthodologique du projet.  
Le dataset produit ici sera ensuite utilisé dans un second notebook dédié à :

- l’**ACP** ;
- la **réduction de dimension** ;
- la **segmentation des pays** via CAH et K-means ;
- la formulation de **recommandations stratégiques** à destination du COMEX.

<a id="top"></a>

<h2 style="color:RGB(170,90,255);">📘 Sommaire</h2>

<ul style="list-style:none; line-height:1.8; font-size:17px; padding-left:0;">

  <li>
    <a href="#etape1" style="color:RGB(170,90,255); text-decoration:none;">📂 Étape 1 • Importation et cadrage du projet</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape1_1" style="color:RGB(170,90,255); text-decoration:none;">1.1 Importation des librairies</a></li>
      <li><a href="#etape1_2" style="color:RGB(170,90,255); text-decoration:none;">1.2 Chargement des données FAO</a></li>
      <li><a href="#etape1_3" style="color:RGB(170,90,255); text-decoration:none;">1.3 Rappel de la problématique métier</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape2" style="color:RGB(120,210,255); text-decoration:none;">🌍 Étape 2 • Compréhension et sélection des variables</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape2_1" style="color:RGB(120,210,255); text-decoration:none;">2.1 Lecture de la structure des fichiers</a></li>
      <li><a href="#etape2_2" style="color:RGB(120,210,255); text-decoration:none;">2.2 Réflexion PESTEL appliquée au projet</a></li>
      <li><a href="#etape2_3" style="color:RGB(120,210,255); text-decoration:none;">2.3 Sélection des variables pertinentes</a></li>
      <li><a href="#etape2_4" style="color:RGB(120,210,255); text-decoration:none;">2.4 Justification métier des variables retenues</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape3" style="color:RGB(255,170,80); text-decoration:none;">🧹 Étape 3 • Préparation et nettoyage des données</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape3_1" style="color:RGB(255,170,80); text-decoration:none;">3.1 Filtrage des indicateurs utiles</a></li>
      <li><a href="#etape3_2" style="color:RGB(255,170,80); text-decoration:none;">3.2 Traitement des doublons</a></li>
      <li><a href="#etape3_3" style="color:RGB(255,170,80); text-decoration:none;">3.3 Contrôle des types et unités</a></li>
      <li><a href="#etape3_4" style="color:RGB(255,170,80); text-decoration:none;">3.4 Gestion des valeurs manquantes</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape4" style="color:RGB(120,255,170); text-decoration:none;">🔗 Étape 4 • Construction du dataset d’analyse</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape4_1" style="color:RGB(120,255,170); text-decoration:none;">4.1 Pivot des données par pays</a></li>
      <li><a href="#etape4_2" style="color:RGB(120,255,170); text-decoration:none;">4.2 Intégration de la population</a></li>
      <li><a href="#etape4_3" style="color:RGB(120,255,170); text-decoration:none;">4.3 Ajout d’éventuelles sources externes</a></li>
      <li><a href="#etape4_4" style="color:RGB(120,255,170); text-decoration:none;">4.4 Vérification du périmètre final (100 pays minimum)</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape5" style="color:RGB(255,120,190); text-decoration:none;">🛠️ Étape 5 • Feature engineering</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape5_1" style="color:RGB(255,120,190); text-decoration:none;">5.1 Création des variables dérivées</a></li>
      <li><a href="#etape5_2" style="color:RGB(255,120,190); text-decoration:none;">5.2 Contrôle de cohérence des nouvelles variables</a></li>
      <li><a href="#etape5_3" style="color:RGB(255,120,190); text-decoration:none;">5.3 Dataset final prêt pour l’ACP</a></li>
    </ul>
  </li>

  <li>
    <a href="#etape6" style="color:RGB(255,210,90); text-decoration:none;">🔎 Étape 6 • Analyse exploratoire des données</a>
    <ul style="list-style:none; margin-left:20px;">
      <li><a href="#etape6_1" style="color:RGB(255,210,90); text-decoration:none;">6.1 Statistiques descriptives</a></li>
      <li><a href="#etape6_2" style="color:RGB(255,210,90); text-decoration:none;">6.2 Distribution des variables</a></li>
      <li><a href="#etape6_3" style="color:RGB(255,210,90); text-decoration:none;">6.3 Détection des outliers</a></li>
      <li><a href="#etape6_4" style="color:RGB(255,210,90); text-decoration:none;">6.4 Première lecture business des profils pays</a></li>
    </ul>
  </li>

  <li>
    <a href="#conclusion1" style="color:RGB(39,245,211); text-decoration:none;">Conclusion du notebook 1</a>
  </li>

</ul>

<a id="etape1"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(168,85,247,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(72,8,92,0.96), rgba(44,7,60,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(82%) sepia(18%) saturate(2017%) hue-rotate(271deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span style="color:#FFFFFF;">📂 Étape 1</span>
    <span>• Importation et cadrage du projet</span>
  </h2>
</div>

<a id="etape1_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(196,132,252,0.28);
  border-radius:12px;
  background:rgba(196,132,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(13%) saturate(1045%) hue-rotate(238deg) brightness(103%) contrast(103%);
      ">
    </a>
    <span>1.1 • Importation des librairies</span>
  </h3>
</div>

In [1]:
# Importation des librairies principales
from IPython.display import display, HTML

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

print("✅ Librairies importées avec succès.")

✅ Librairies importées avec succès.

In [2]:
# Configuration de l'affichage pandas
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 120)

print("✅ Options d'affichage pandas configurées.")

✅ Options d'affichage pandas configurées.

<a id="etape1_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(196,132,252,0.28);
  border-radius:12px;
  background:rgba(196,132,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(13%) saturate(1045%) hue-rotate(238deg) brightness(103%) contrast(103%);
      ">
    </a>
    <span>1.2 • Chargement des données FAO</span>
  </h3>
</div>

In [3]:
# Chargement des fichiers CSV
dispo = pd.read_csv(
    "data/DisponibiliteAlimentaire_2017.csv",
    sep=","
)

population = pd.read_csv(
    "data/Population_2000_2018.csv",
    sep=","
)

print("✅ Fichiers chargés avec succès.")

✅ Fichiers chargés avec succès.

In [4]:
# Dimensions des datasets
print("Dimensions du fichier Disponibilité alimentaire :", dispo.shape)
print("Dimensions du fichier Population :", population.shape)

Dimensions du fichier Disponibilité alimentaire : (176600, 14)
Dimensions du fichier Population : (4411, 15)

In [5]:
# Aperçu des premières lignes du fichier disponibilité alimentaire
dispo.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2511,Blé et produits,2017,2017,Milliers de tonnes,4281.0,S,Données standardisées
1,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,2302.0,S,Données standardisées
2,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2511,Blé et produits,2017,2017,Milliers de tonnes,-119.0,S,Données standardisées
3,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5911,Exportations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,0.0,S,Données standardisées
4,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé et produits,2017,2017,Milliers de tonnes,6701.0,S,Données standardisées

In [6]:
# Aperçu des premières lignes du fichier population

population.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2000,2000,1000 personnes,20779.953,X,Sources internationales sûres,NaN
1,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2001,2001,1000 personnes,21606.988,X,Sources internationales sûres,NaN
2,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2002,2002,1000 personnes,22600.770,X,Sources internationales sûres,NaN
3,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2003,2003,1000 personnes,23680.871,X,Sources internationales sûres,NaN
4,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2004,2004,1000 personnes,24726.684,X,Sources internationales sûres,NaN

In [7]:
# Informations générales sur le fichier disponibilité alimentaire
dispo.info()

<class 'pandas.DataFrame'>
RangeIndex: 176600 entries, 0 to 176599
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Code Domaine            176600 non-null  str
 1   Domaine                 176600 non-null  str
 2   Code zone               176600 non-null  int64
 3   Zone                    176600 non-null  str
 4   Code Élément            176600 non-null  int64
 5   Élément                 176600 non-null  str
 6   Code Produit            176600 non-null  int64
 7   Produit                 176600 non-null  str
 8   Code année              176600 non-null  int64
 9   Année                   176600 non-null  int64
 10  Unité                   176600 non-null  str
 11  Valeur                  176600 non-null  float64
 12  Symbole                 176600 non-null  str
 13  Description du Symbole  176600 non-null  str
dtypes: float64(1), int64(5), str(8)
memory usage: 18.9 MB

In [8]:
# Informations générales sur le fichier population
population.info()

<class 'pandas.DataFrame'>
RangeIndex: 4411 entries, 0 to 4410
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            4411 non-null   str
 1   Domaine                 4411 non-null   str
 2   Code zone               4411 non-null   int64
 3   Zone                    4411 non-null   str
 4   Code Élément            4411 non-null   int64
 5   Élément                 4411 non-null   str
 6   Code Produit            4411 non-null   int64
 7   Produit                 4411 non-null   str
 8   Code année              4411 non-null   int64
 9   Année                   4411 non-null   int64
 10  Unité                   4411 non-null   str
 11  Valeur                  4411 non-null   float64
 12  Symbole                 4411 non-null   str
 13  Description du Symbole  4411 non-null   str
 14  Note                    258 non-null    str
dtypes: float64(1), int64(5), str(9)
memory usage: 517.0 KB

In [9]:
# Vérification des valeurs manquantes dans les fichiers sources
missing_dispo = dispo.isnull().sum().sort_values(ascending=False)
missing_population = population.isnull().sum().sort_values(ascending=False)

display(HTML("<h3 style='color:#C084FC;'>Valeurs manquantes — Disponibilité alimentaire</h3>"))
display(missing_dispo[missing_dispo > 0])

display(HTML("<h3 style='color:#C084FC;'>Valeurs manquantes — Population</h3>"))
display(missing_population[missing_population > 0])

Series([], dtype: int64)

Note    4153
dtype: int64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(31,14,54,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(196,132,252,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">📂</span>
    <b style="font-size:19px; color:#E9C7FF;">Étape 1.2 — Chargement des données FAO</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Deux fichiers sources ont été importés afin de construire la base de travail du projet :
    un fichier de <b style="color:#D8B4FE;">disponibilité alimentaire</b> et un fichier de
    <b style="color:#D8B4FE;">population</b>.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(168,85,247,0.08);
      border:1px solid rgba(168,85,247,0.28);
    ">
      <div style="font-weight:700; color:#E9C7FF; margin-bottom:6px;">🍗 Disponibilité alimentaire</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>176 600</b> lignes</li>
        <li><b>14</b> colonnes</li>
        <li>Données alimentaires par pays, produit et indicateur</li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🌍 Population</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>4 411</b> lignes</li>
        <li><b>15</b> colonnes</li>
        <li>Données de population par pays et par année</li>
      </ul>
    </div>

  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Contrôle du chargement :</b><br>
    Les deux fichiers ont été chargés correctement. Les premières lignes confirment que les données contiennent
    les colonnes attendues, notamment <b>Zone</b>, <b>Produit</b>, <b>Élément</b>, <b>Année</b>, <b>Unité</b> et <b>Valeur</b>.
  </div>

  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.30);
  ">
    🔎 <b style="color:#FDE68A;">Lecture initiale :</b><br>
    Le fichier de disponibilité alimentaire ne présente pas de valeurs manquantes visibles sur les colonnes utiles.
    Dans le fichier population, la colonne <b>Note</b> contient des valeurs manquantes, mais cette colonne est descriptive
    et ne sera pas utilisée pour l’analyse.
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Les fichiers sources sont exploitables pour démarrer l’étude. La prochaine étape consiste à comprendre leur structure,
    identifier les indicateurs disponibles et sélectionner les variables pertinentes pour une stratégie d’exportation de volaille.
  </div>

</div>

<a id="etape1_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(196,132,252,0.28);
  border-radius:12px;
  background:rgba(196,132,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(13%) saturate(1045%) hue-rotate(238deg) brightness(103%) contrast(103%);
      ">
    </a>
    <span>1.3 • Rappel de la problématique métier</span>
  </h3>
</div>

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(53,18,72,0.96), rgba(20,18,28,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(236,72,153,0.32);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:21px;">🐔</span>
    <b style="font-size:19px; color:#F9A8D4;">Étape 1.3 — Rappel de la problématique métier</b>
  </div>
  <p style="margin:0 0 12px 0;">
    L’entreprise fictive <b style="color:#FDE68A;">La poule qui chante</b> souhaite développer son activité
    à l’international. L’objectif n’est pas encore de réaliser une étude de marché détaillée pays par pays,
    mais d’identifier des <b style="color:#F9A8D4;">groupes de pays prometteurs</b> pour l’exportation de poulets.
  </p>

  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(236,72,153,0.08);
      border:1px solid rgba(236,72,153,0.28);
    ">
      <div style="font-weight:700; color:#F9A8D4; margin-bottom:6px;">🎯 Objectif business</div>
      <p style="margin:0;">
        Repérer les pays ou groupes de pays qui présentent un potentiel intéressant pour une future stratégie
        d’exportation de volaille.
      </p>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">📊 Approche data</div>
      <p style="margin:0;">
        Construire un dataset pays à partir d’indicateurs alimentaires, démographiques et commerciaux issus
        principalement des données FAO.
      </p>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">🌍 Finalité stratégique</div>
      <p style="margin:0;">
        Préparer une segmentation des pays afin d’aider le COMEX à prioriser les marchés à étudier plus en détail.
      </p>
    </div>
  </div>

  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.30);
  ">
    🧭 <b style="color:#FDE68A;">Démarche retenue :</b>
    <ul style="margin:8px 0 0 0; padding-left:20px;">
      <li>analyser les fichiers sources disponibles ;</li>
      <li>sélectionner au moins <b>8 variables pertinentes</b> pour la problématique ;</li>
      <li>nettoyer les données et retirer les pays peu exploitables ou aberrants ;</li>
      <li>créer des variables dérivées utiles à l’analyse ;</li>
      <li>exporter un dataset final propre pour l’ACP et le clustering.</li>
    </ul>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(168,85,247,0.08);
    border:1px solid rgba(168,85,247,0.28);
  ">
    👉 <b style="color:#D8B4FE;">En clair :</b><br>
    Ce premier notebook sert à construire une base fiable et cohérente. Le second notebook utilisera ensuite ce dataset
    pour réaliser l’ACP, le clustering et les recommandations de pays à prioriser.
  </div>

</div>

<a id="etape2"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(56,189,248,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(6,28,50,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(78%) sepia(40%) saturate(1318%) hue-rotate(166deg) brightness(101%) contrast(100%);
      ">
    </a>
    <span style="color:#FFFFFF;">🌍 Étape 2</span>
    <span>• Compréhension et sélection des variables</span>
  </h2>
</div>

<a id="etape2_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.1 • Lecture de la structure des fichiers</span>
  </h3>
</div>

In [10]:
# Liste des colonnes du fichier disponibilité alimentaire
dispo.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole'],
      dtype='str')

In [11]:
# Liste des colonnes du fichier population
population.columns

Index(['Code Domaine', 'Domaine', 'Code zone', 'Zone', 'Code Élément',
       'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité',
       'Valeur', 'Symbole', 'Description du Symbole', 'Note'],
      dtype='str')

In [12]:
# Nombre de pays présents dans chaque fichier
nb_pays_dispo = dispo["Zone"].nunique()
nb_pays_population = population["Zone"].nunique()

print(f"Nombre de pays dans le fichier disponibilité alimentaire : {nb_pays_dispo}")
print(f"Nombre de pays dans le fichier population : {nb_pays_population}")

Nombre de pays dans le fichier disponibilité alimentaire : 174
Nombre de pays dans le fichier population : 238

In [13]:
# Modalités disponibles dans la colonne Élément
dispo["Élément"].dropna().unique()

<StringArray>
[                                                   'Production',
                                       'Importations - Quantité',
                                            'Variation de stock',
                                       'Exportations - Quantité',
                                      'Disponibilité intérieure',
                                         'Aliments pour animaux',
                                                      'Semences',
                                                        'Pertes',
                                                       'Résidus',
                                                    'Nourriture',
        'Disponibilité alimentaire en quantité (kg/personne/an)',
                'Disponibilité alimentaire (Kcal/personne/jour)',
      'Disponibilité de protéines en quantité (g/personne/jour)',
 'Disponibilité de matière grasse en quantité (g/personne/jour)',
                                                    'Traitement',
                         'Autres utilisations (non alimentaire)',
                                   'Alimentation pour touristes']
Length: 17, dtype: str

In [14]:
# Modalités disponibles dans la colonne Produit

dispo["Produit"].dropna().unique()

<StringArray>
[                'Blé et produits',                 'Riz et produits',
                'Orge et produits',                'Maïs et produits',
              'Seigle et produits',                          'Avoine',
              'Millet et produits',              'Sorgho et produits',
                'Céréales, Autres',     'Pommes de Terre et produits',
                         'Ignames',                     'Racines nda',
                    'Sucre, canne',                'Sucre, betterave',
                   'Sucre Eq Brut',              'Edulcorants Autres',
                            'Miel',                        'Haricots',
                            'Pois', 'Légumineuses Autres et produits',
                'Noix et produits',                            'Soja',
          'Arachides Decortiquees',            'Graines de tournesol',
          'Graines Colza/Moutarde',                'Graines de coton',
              'Coco (Incl Coprah)',                          'Sésame',
                          'Olives',        'Plantes Oleiferes, Autre',
                   'Huile de Soja',                'Huile d'Arachide',
              'Huile de Tournesol',         'Huile de Colza&Moutarde',
          'Huile Graines de Coton',              'Huile de Palmistes',
                  'Huile de Palme',                   'Huile de Coco',
                 'Huile de Sésame',                   'Huile d'Olive',
             'Huile de Son de Riz',          'Huile de Germe de Maïs',
         'Huil Plantes Oleif Autr',             'Tomates et produits',
                         'Oignons',                 'Légumes, Autres',
             'Oranges, Mandarines',     'Citrons & Limes et produits',
        'Pamplemousse et produits',                 'Agrumes, Autres',
                         'Bananes',              'Pommes et produits',
              'Ananas et produits',                          'Dattes',
                          'Raisin',                  'Fruits, Autres',
                'Café et produits',       'Feve de Cacao et produits',
                             'Thé',                          'Poivre',
                         'Piments',                        'Girofles',
                  'Épices, Autres',                             'Vin',
                           'Bière',              'Boissons Fermentés',
            'Boissons Alcooliques',          'Alcool, non Comestible',
                'Viande de Bovins',          'Viande d'Ovins/Caprins',
                'Viande de Suides',             'Viande de Volailles',
                   'Viande, Autre',                'Abats Comestible',
                    'Beurre, Ghee',                           'Crème',
          'Graisses Animales Crue',                           'Oeufs',
              'Lait - Excl Beurre',              'Poissons Eau Douce',
           'Aliments pour enfants',                    'Miscellanees',
              'Manioc et produits',                  'Patates douces',
                       'Palmistes',               'Bananes plantains',
              'Huiles de Poissons',        'Huiles de Foie de Poisso',
                       'Perciform',             'Poissons Pelagiques',
         'Poissons Marins, Autres',                       'Crustacés',
                    'Cephalopodes',              'Mollusques, Autres',
        'Animaux Aquatiques Autre',              'Plantes Aquatiques',
            'Sucre non centrifugé',          'Viande de Anim Aquatiq']
Length: 98, dtype: str

In [15]:
# Nombre d'occurrences par élément
dispo["Élément"].value_counts()

Élément
Disponibilité intérieure                                         15905
Importations - Quantité                                          15260
Disponibilité alimentaire en quantité (kg/personne/an)           14618
Disponibilité de matière grasse en quantité (g/personne/jour)    14512
Disponibilité de protéines en quantité (g/personne/jour)         14507
Nourriture                                                       14498
Disponibilité alimentaire (Kcal/personne/jour)                   14476
Résidus                                                          12567
Exportations - Quantité                                          12113
Variation de stock                                               11299
Production                                                       10334
Pertes                                                            5813
Alimentation pour touristes                                       5560
Autres utilisations (non alimentaire)                             5292
Aliments pour animaux                                             4188
Traitement                                                        3546
Semences                                                          2112
Name: count, dtype: int64

In [16]:
# Nombre d'occurrences par produit
dispo["Produit"].value_counts().head(30)

Produit
Maïs et produits                   2593
Blé et produits                    2581
Pommes de Terre et produits        2486
Riz et produits                    2452
Lait - Excl Beurre                 2395
Oeufs                              2347
Légumineuses Autres et produits    2336
Orge et produits                   2301
Soja                               2222
Céréales, Autres                   2206
Légumes, Autres                    2204
Fruits, Autres                     2198
Arachides Decortiquees             2197
Edulcorants Autres                 2194
Haricots                           2141
Sucre Eq Brut                      2137
Graisses Animales Crue             2137
Feve de Cacao et produits          2088
Huil Plantes Oleif Autr            2083
Plantes Oleiferes, Autre           2077
Viande de Bovins                   2065
Viande de Volailles                2061
Avoine                             2060
Coco (Incl Coprah)                 2051
Tomates et produits                2046
Raisin                             2035
Graines Colza/Moutarde             2028
Oranges, Mandarines                2027
Viande de Suides                   2009
Pommes et produits                 2005
Name: count, dtype: int64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🔎</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.1 — Lecture de la structure des fichiers</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Cette étape permet de comprendre la structure des deux fichiers sources avant de sélectionner les variables utiles.
    Les fichiers disposent d’une organisation similaire : chaque ligne correspond à une combinaison
    <b style="color:#7DD3FC;">pays / produit / indicateur / année</b>.
  </p>

  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🍗 Fichier disponibilité alimentaire</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>174</b> pays identifiés</li>
        <li><b>17</b> types d’indicateurs disponibles</li>
        <li><b>98</b> produits alimentaires différents</li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(168,85,247,0.08);
      border:1px solid rgba(168,85,247,0.28);
    ">
      <div style="font-weight:700; color:#E9C7FF; margin-bottom:6px;">🌍 Fichier population</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>238</b> pays ou zones identifiés</li>
        <li>Données disponibles sur plusieurs années</li>
        <li>Unité exprimée en <b>1000 personnes</b></li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Constat principal :</b><br>
    Les deux fichiers contiennent une colonne <b>Zone</b>, ce qui permettra de les rapprocher par pays.
    Le fichier de disponibilité alimentaire contient également les colonnes <b>Produit</b> et <b>Élément</b>,
    indispensables pour filtrer les données liées à la volaille.
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.30);
  ">
    📌 <b style="color:#FDE68A;">Point d’attention :</b><br>
    Le nombre de pays est différent entre les deux fichiers. Il faudra donc vérifier, lors de la construction du dataset final,
    quels pays sont présents dans les deux sources et supprimer ceux pour lesquels les informations utiles sont incomplètes.
  </div>

  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(56,189,248,0.08);
    border:1px solid rgba(56,189,248,0.26);
  ">
    👉 <b style="color:#BFE9FF;">En clair :</b><br>
    Les données sont bien structurées pour construire une base d’analyse par pays. La suite consiste à identifier
    les produits liés à la volaille et les indicateurs les plus pertinents pour répondre à la problématique d’exportation.
  </div>

</div>

<a id="etape2_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.2 • Réflexion PESTEL appliquée au projet</span>
  </h3>
</div>

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🌐</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.2 — Réflexion PESTEL appliquée au projet</b>
  </div>
  <p style="margin:0 0 14px 0;">
    Avant de sélectionner les variables, une réflexion PESTEL permet de cadrer les dimensions utiles à une stratégie
    d’exportation. Toutes les dimensions ne sont pas directement mesurables avec les fichiers FAO, mais elles permettent
    de justifier les indicateurs retenus.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="padding:12px 2px; border-radius:12px; background:rgba(236,72,153,0.08); border:1px solid rgba(236,72,153,0.28);">
      <div style="font-weight:700; color:#F9A8D4; margin-bottom:6px;">🏛️ Politique</div>
      <p style="margin:0;">La stabilité politique, les réglementations sanitaires et les barrières douanières peuvent influencer la capacité d’une entreprise à exporter.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(250,204,21,0.08); border:1px solid rgba(250,204,21,0.28);">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">💰 Économique</div>
      <p style="margin:0;">Le niveau d’importation, la production locale et la dépendance aux importations permettent d’évaluer l’attractivité d’un marché.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(34,197,94,0.08); border:1px solid rgba(34,197,94,0.28);">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">👥 Sociodémographique</div>
      <p style="margin:0;">La taille de la population et les habitudes alimentaires permettent d’estimer le potentiel de demande.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(56,189,248,0.08); border:1px solid rgba(56,189,248,0.28);">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🚚 Technologique</div>
      <p style="margin:0;">La logistique, la distribution et la chaîne du froid peuvent influencer la faisabilité d’une stratégie d’exportation.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(132,204,22,0.08); border:1px solid rgba(132,204,22,0.28);">
      <div style="font-weight:700; color:#BEF264; margin-bottom:6px;">🌱 Environnemental</div>
      <p style="margin:0;">La capacité de production locale, les contraintes climatiques et les ressources disponibles peuvent influencer le besoin d’importation.</p>
    </div>
    <div style="padding:12px 2px; border-radius:12px; background:rgba(168,85,247,0.08); border:1px solid rgba(168,85,247,0.28);">
      <div style="font-weight:700; color:#E9C7FF; margin-bottom:6px;">⚖️ Légal</div>
      <p style="margin:0;">Les normes sanitaires, les accords commerciaux et les règles d’importation peuvent impacter la faisabilité de l’exportation.</p>
    </div>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(56,189,248,0.08);
    border:1px solid rgba(56,189,248,0.28);
  ">
    👉 <b style="color:#BFE9FF;">En clair :</b><br>
    Dans ce notebook, l’analyse se concentre surtout sur les dimensions <b>alimentaires</b>,
    <b>économiques</b> et <b>démographiques</b>, car ce sont celles qui sont directement exploitables
    à partir des données disponibles.
  </div>

</div>

<a id="etape2_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.3 • Sélection des variables pertinentes</span>
  </h3>
</div>

In [17]:
# Liste des indicateurs disponibles dans les données FAO
elements_disponibles = sorted(dispo["Élément"].dropna().unique())

for element in elements_disponibles:
    print(element)

Alimentation pour touristes
Aliments pour animaux
Autres utilisations (non alimentaire)
Disponibilité alimentaire (Kcal/personne/jour)
Disponibilité alimentaire en quantité (kg/personne/an)
Disponibilité de matière grasse en quantité (g/personne/jour)
Disponibilité de protéines en quantité (g/personne/jour)
Disponibilité intérieure
Exportations - Quantité
Importations - Quantité
Nourriture
Pertes
Production
Résidus
Semences
Traitement
Variation de stock

In [18]:
# Identification des produits liés à la volaille
produits_volaille = dispo[
    dispo["Produit"].str.contains("volaille|poulet|viande de volailles", case=False, na=False)
]["Produit"].unique()

produits_volaille

<StringArray>
['Viande de Volailles']
Length: 1, dtype: str

In [19]:
# Filtrage des données liées à la viande de volailles
volaille = dispo[dispo["Produit"] == "Viande de Volailles"].copy()

print("Dimensions du sous-ensemble volaille :", volaille.shape)
volaille.head()

Dimensions du sous-ensemble volaille : (2061, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.0,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.0,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.0,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.0,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.0,S,Données standardisées

In [20]:
# Indicateurs disponibles pour la viande de volailles
volaille["Élément"].value_counts()

Élément
Disponibilité alimentaire en quantité (kg/personne/an)           172
Disponibilité alimentaire (Kcal/personne/jour)                   172
Disponibilité de protéines en quantité (g/personne/jour)         172
Disponibilité de matière grasse en quantité (g/personne/jour)    172
Importations - Quantité                                          170
Disponibilité intérieure                                         170
Nourriture                                                       170
Variation de stock                                               169
Production                                                       168
Résidus                                                          164
Exportations - Quantité                                          135
Alimentation pour touristes                                       78
Pertes                                                            67
Traitement                                                        46
Autres utilisations (non alimentaire)                             34
Aliments pour animaux                                              1
Semences                                                           1
Name: count, dtype: int64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🎯</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.3 — Sélection des variables pertinentes</b>
  </div>

  <p style="margin:0 0 12px 0;">
    La sélection des variables commence par l’identification du produit correspondant à la problématique métier :
    <b style="color:#FDE68A;">Viande de Volailles</b>. Ce sous-ensemble servira de base pour construire les indicateurs
    utiles à l’analyse de marché.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:4px 4px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🍗 Produit ciblé</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Produit identifié : <b>Viande de Volailles</b></li>
        <li>Sous-ensemble obtenu : <b>2 061</b> lignes</li>
        <li>Données disponibles sur plusieurs indicateurs FAO</li>
      </ul>
    </div>
    <div style="
      padding:4px 4px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">📊 Indicateurs clés disponibles</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Disponibilité alimentaire</li>
        <li>Production</li>
        <li>Importations / exportations</li>
        <li>Disponibilité intérieure</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.30);
  ">
    📌 <b style="color:#FDE68A;">Lecture des données :</b><br>
    Les indicateurs les plus complets pour la viande de volailles concernent la disponibilité alimentaire
    en quantité, en calories, en protéines et en matières grasses. Les indicateurs commerciaux et productifs
    comme les importations, la production, les exportations et la disponibilité intérieure sont également disponibles.
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Le produit cible est bien présent dans les données. Les indicateurs disponibles permettent de construire une base
    cohérente pour évaluer à la fois le potentiel de consommation, le niveau de production locale et la dépendance
    potentielle aux importations.
  </div>
</div>

<a id="etape2_4"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(125,211,252,0.28);
  border-radius:12px;
  background:rgba(125,211,252,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(86%) sepia(14%) saturate(988%) hue-rotate(174deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>2.4 • Justification métier des variables retenues</span>
  </h3>
</div>

In [21]:
# Première sélection d'indicateurs pertinents pour l'analyse
elements_retenus = [
    "Disponibilité alimentaire (Kcal/personne/jour)",
    "Disponibilité alimentaire en quantité (kg/personne/an)",
    "Disponibilité de protéines en quantité (g/personne/jour)",
    "Disponibilité de matière grasse en quantité (g/personne/jour)",
    "Importations - Quantité",
    "Production",
    "Exportations - Quantité",
    "Disponibilité intérieure"
]

elements_retenus

['Disponibilité alimentaire (Kcal/personne/jour)',
 'Disponibilité alimentaire en quantité (kg/personne/an)',
 'Disponibilité de protéines en quantité (g/personne/jour)',
 'Disponibilité de matière grasse en quantité (g/personne/jour)',
 'Importations - Quantité',
 'Production',
 'Exportations - Quantité',
 'Disponibilité intérieure']

In [22]:
# Vérification de la présence des indicateurs retenus dans le fichier
elements_existants = dispo["Élément"].unique()

for element in elements_retenus:
    if element in elements_existants:
        print(f"✅ Présent : {element}")
    else:
        print(f"❌ Absent ou nom différent : {element}")

✅ Présent : Disponibilité alimentaire (Kcal/personne/jour)
✅ Présent : Disponibilité alimentaire en quantité (kg/personne/an)
✅ Présent : Disponibilité de protéines en quantité (g/personne/jour)
✅ Présent : Disponibilité de matière grasse en quantité (g/personne/jour)
✅ Présent : Importations - Quantité
✅ Présent : Production
✅ Présent : Exportations - Quantité
✅ Présent : Disponibilité intérieure

In [23]:
# Sélection des données volaille correspondant aux indicateurs retenus
volaille_selected = volaille[volaille["Élément"].isin(elements_retenus)].copy()

print("Dimensions après sélection :", volaille_selected.shape)
volaille_selected.head()

Dimensions après sélection : (1331, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
658,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/personne/an),2734,Viande de Volailles,2017,2017,kg,1.53,Fc,Donnée calculée
659,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2017,2017,Kcal/personne/jour,5.00,Fc,Donnée calculée

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(7,55,92,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(56,189,248,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧩</span>
    <b style="font-size:19px; color:#BFE9FF;">Étape 2.4 — Justification métier des variables retenues</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Une première sélection de variables a été réalisée afin de conserver les indicateurs les plus utiles pour une
    stratégie d’exportation de volaille. Ces variables seront ensuite nettoyées, transformées et complétées par des
    variables dérivées.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(280px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 4px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">🥗 Consommation et disponibilité</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Disponibilité alimentaire en quantité</li>
        <li>Disponibilité alimentaire en kcal</li>
        <li>Disponibilité en protéines</li>
        <li>Disponibilité en matières grasses</li>
      </ul>
    </div>
    <div style="
      padding:12px 4px;
      border-radius:12px;
      background:rgba(250,204,21,0.08);
      border:1px solid rgba(250,204,21,0.28);
    ">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">🏭 Offre locale et commerce</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Production</li>
        <li>Importations - Quantité</li>
        <li>Exportations - Quantité</li>
        <li>Disponibilité intérieure</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(56,189,248,0.08);
    border:1px solid rgba(56,189,248,0.28);
  ">
    ✅ <b style="color:#BFE9FF;">Contrôle de présence :</b><br>
    Les <b>8 indicateurs sélectionnés</b> sont bien présents dans le fichier FAO. Après filtrage sur la viande de volailles
    et les indicateurs retenus, le sous-ensemble contient <b>1 331</b> lignes.
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(168,85,247,0.08);
    border:1px solid rgba(168,85,247,0.28);
  ">
    🧠 <b style="color:#E9C7FF;">Pourquoi ces variables ?</b><br>
    Elles permettent de mesurer plusieurs dimensions complémentaires :
    <ul style="margin:8px 0 0 0; padding-left:20px;">
      <li>le potentiel de consommation de volaille ;</li>
      <li>la place de la volaille dans l’alimentation ;</li>
      <li>la capacité de production locale ;</li>
      <li>la dépendance potentielle aux importations ;</li>
      <li>le profil commercial du pays sur ce produit.</li>
    </ul>
  </div>
  <div style="
    margin-top:14px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Cette sélection constitue une première base solide pour construire le dataset final. Les variables seront ensuite
    pivotées par pays, croisées avec la population, puis enrichies avec des indicateurs dérivés comme le taux de dépendance
    aux importations ou le taux d’autosuffisance.
  </div>

</div>

<a id="etape3"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(251,146,60,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(48,21,6,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(74%) sepia(53%) saturate(1536%) hue-rotate(340deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span style="color:#FFFFFF;">🧹 Étape 3</span>
    <span>• Préparation et nettoyage des données</span>
  </h2>
</div>

<a id="etape3_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.1 • Filtrage des indicateurs utiles</span>
  </h3>
</div>

In [24]:
# Copie de travail des datasets sources
dispo_clean = dispo.copy()
population_clean = population.copy()

print("✅ Copies de travail créées.")

✅ Copies de travail créées.

In [25]:
# Vérification rapide des années disponibles
print("Années disponibles dans le fichier disponibilité alimentaire :")
print(sorted(dispo_clean["Année"].unique())[:10], "...")

print("\nAnnées disponibles dans le fichier population :")
print(sorted(population_clean["Année"].unique())[-10:])

Années disponibles dans le fichier disponibilité alimentaire :
[np.int64(2017)] ...

Années disponibles dans le fichier population :
[np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018)]

In [26]:
# Filtrage de la population sur l'année 2017
population_2017 = population_clean[population_clean["Année"] == 2017].copy()

print("Dimensions du fichier population 2017 :", population_2017.shape)
population_2017.head()

Dimensions du fichier population 2017 : (236, 15)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
17,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,36296.113,X,Sources internationales sûres,NaN
36,OA,Séries temporelles annuelles,202,Afrique du Sud,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,57009.756,X,Sources internationales sûres,NaN
55,OA,Séries temporelles annuelles,3,Albanie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,2884.169,X,Sources internationales sûres,NaN
74,OA,Séries temporelles annuelles,4,Algérie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,41389.189,X,Sources internationales sûres,NaN
93,OA,Séries temporelles annuelles,79,Allemagne,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,82658.409,X,Sources internationales sûres,NaN

In [27]:
# Vérification du type de produit retenu
produits_volaille = dispo_clean[
    dispo_clean["Produit"].str.contains("volaille|poulet|viande de volailles", case=False, na=False)
]["Produit"].unique()

produits_volaille

<StringArray>
['Viande de Volailles']
Length: 1, dtype: str

In [28]:
# Filtrage des données sur le produit "Viande de Volailles"
volaille = dispo_clean[dispo_clean["Produit"] == "Viande de Volailles"].copy()

print("Dimensions du sous-ensemble volaille :", volaille.shape)
volaille.head()

Dimensions du sous-ensemble volaille : (2061, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.0,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.0,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.0,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.0,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.0,S,Données standardisées

In [29]:
# Liste des 8 indicateurs retenus pour l'analyse
elements_retenus = [
    "Disponibilité alimentaire (Kcal/personne/jour)",
    "Disponibilité alimentaire en quantité (kg/personne/an)",
    "Disponibilité de protéines en quantité (g/personne/jour)",
    "Disponibilité de matière grasse en quantité (g/personne/jour)",
    "Importations - Quantité",
    "Production",
    "Exportations - Quantité",
    "Disponibilité intérieure"
]

elements_retenus

['Disponibilité alimentaire (Kcal/personne/jour)',
 'Disponibilité alimentaire en quantité (kg/personne/an)',
 'Disponibilité de protéines en quantité (g/personne/jour)',
 'Disponibilité de matière grasse en quantité (g/personne/jour)',
 'Importations - Quantité',
 'Production',
 'Exportations - Quantité',
 'Disponibilité intérieure']

In [30]:
# Filtrage sur les 8 indicateurs retenus
volaille_selected = volaille[
    volaille["Élément"].isin(elements_retenus)
].copy()

print("Dimensions après filtrage produit + indicateurs :", volaille_selected.shape)
volaille_selected.head()

Dimensions après filtrage produit + indicateurs : (1331, 14)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
658,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/personne/an),2734,Viande de Volailles,2017,2017,kg,1.53,Fc,Donnée calculée
659,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2017,2017,Kcal/personne/jour,5.00,Fc,Donnée calculée

In [31]:
# Vérification du nombre de pays présents dans le sous-ensemble filtré
nb_pays_volaille = volaille_selected["Zone"].nunique()
nb_pays_pop_2017 = population_2017["Zone"].nunique()

print(f"Nombre de pays dans volaille_selected : {nb_pays_volaille}")
print(f"Nombre de pays dans population_2017 : {nb_pays_pop_2017}")

Nombre de pays dans volaille_selected : 172
Nombre de pays dans population_2017 : 236

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧹</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.1 — Filtrage des indicateurs utiles</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Le périmètre de travail a été resserré afin de ne conserver que les données directement utiles à la problématique :
    le produit <b style="color:#FDE68A;">Viande de Volailles</b>, les <b>8 indicateurs retenus</b> et la population sur l’année <b>2017</b>.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">🍗 Sous-ensemble volaille</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Produit ciblé identifié : <b>Viande de Volailles</b></li>
        <li>Sous-ensemble initial : <b>2 061</b> lignes</li>
        <li>Après filtrage sur les 8 indicateurs : <b>1 331</b> lignes</li>
        <li>Pays présents : <b>172</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🌍 Population 2017</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Pays/zones présents : <b>236</b></li>
        <li>Année retenue : <b>2017</b></li>
        <li>Unité : <b>1000 personnes</b></li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Résultat :</b><br>
    Le filtrage a bien recentré l’analyse sur le bon produit et les bons indicateurs. Le dataset de travail est désormais
    plus ciblé, plus lisible et plus cohérent pour les étapes suivantes.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Point de vigilance :</b><br>
    Le nombre de pays disponibles dans la population 2017 (<b>236</b>) est supérieur à celui du sous-ensemble volaille (<b>172</b>).
    Il faudra donc vérifier plus tard quels pays sont réellement exploitables dans les deux sources.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Le filtrage est réussi. À ce stade, rien ne justifie encore d’exclure des pays, mais la comparaison des périmètres
    montre déjà qu’un futur filtre qualité sera nécessaire après la fusion.
  </div>
</div>

<a id="etape3_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.2 • Traitement des doublons</span>
  </h3>
</div>

In [32]:
# Vérification des doublons exacts dans le sous-ensemble volaille_selected
duplicated_volaille = volaille_selected.duplicated().sum()
print("Nombre de doublons exacts dans volaille_selected :", duplicated_volaille)

Nombre de doublons exacts dans volaille_selected : 0

In [33]:
# Vérification des doublons exacts dans population_2017
duplicated_population = population_2017.duplicated().sum()
print("Nombre de doublons exacts dans population_2017 :", duplicated_population)

Nombre de doublons exacts dans population_2017 : 0

In [34]:
# Vérification de doublons logiques sur les clés métier
# Un pays ne devrait apparaître qu'une fois par indicateur dans volaille_selected
doublons_logiques_volaille = volaille_selected.duplicated(
    subset=["Zone", "Élément"]
).sum()

print("Nombre de doublons logiques (Zone + Élément) dans volaille_selected :", doublons_logiques_volaille)

Nombre de doublons logiques (Zone + Élément) dans volaille_selected : 0

In [35]:
# Pour la population 2017, un pays devrait apparaître une seule fois
doublons_logiques_population = population_2017.duplicated(
    subset=["Zone"]
).sum()

print("Nombre de doublons logiques (Zone) dans population_2017 :", doublons_logiques_population)

Nombre de doublons logiques (Zone) dans population_2017 : 0

In [36]:
# Suppression des doublons exacts si nécessaire
volaille_selected = volaille_selected.drop_duplicates().copy()
population_2017 = population_2017.drop_duplicates().copy()

print("✅ Doublons exacts supprimés si nécessaire.")
print("Nouvelles dimensions volaille_selected :", volaille_selected.shape)
print("Nouvelles dimensions population_2017 :", population_2017.shape)

✅ Doublons exacts supprimés si nécessaire.
Nouvelles dimensions volaille_selected : (1331, 14)
Nouvelles dimensions population_2017 : (236, 15)

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧾</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.2 — Traitement des doublons</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Les doublons exacts et les doublons logiques ont été vérifiés afin de s’assurer qu’un même pays ne soit pas
    représenté plusieurs fois pour un même indicateur.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(260px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">🍗 Volaille sélectionnée</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Doublons exacts : <b>0</b></li>
        <li>Doublons logiques (Zone + Élément) : <b>0</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(56,189,248,0.08);
      border:1px solid rgba(56,189,248,0.28);
    ">
      <div style="font-weight:700; color:#BFE9FF; margin-bottom:6px;">🌍 Population 2017</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Doublons exacts : <b>0</b></li>
        <li>Doublons logiques (Zone) : <b>0</b></li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Conclusion :</b><br>
    Les deux sous-ensembles sont propres sur la question des doublons. Aucune anomalie de duplication n’a été détectée,
    ni au niveau exact, ni au niveau logique.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Interprétation :</b><br>
    C’est un très bon signal qualité : les observations semblent bien structurées, ce qui limite le risque de biaiser
    le futur dataset pays par une répétition artificielle d’informations.
  </div>
</div>

<a id="etape3_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.3 • Contrôle des types et unités</span>
  </h3>
</div>

In [37]:
# Vérification des types
print("Types de volaille_selected :")
print(volaille_selected.dtypes)

print("\nTypes de population_2017 :")
print(population_2017.dtypes)

Types de volaille_selected :
Code Domaine                  str
Domaine                       str
Code zone                   int64
Zone                          str
Code Élément                int64
Élément                       str
Code Produit                int64
Produit                       str
Code année                  int64
Année                       int64
Unité                         str
Valeur                    float64
Symbole                       str
Description du Symbole        str
dtype: object

Types de population_2017 :
Code Domaine                  str
Domaine                       str
Code zone                   int64
Zone                          str
Code Élément                int64
Élément                       str
Code Produit                int64
Produit                       str
Code année                  int64
Année                       int64
Unité                         str
Valeur                    float64
Symbole                       str
Description du Symbole        str
Note                          str
dtype: object

In [38]:
# Conversion explicite de la colonne Valeur en numérique si nécessaire
volaille_selected["Valeur"] = pd.to_numeric(volaille_selected["Valeur"], errors="coerce")
population_2017["Valeur"] = pd.to_numeric(population_2017["Valeur"], errors="coerce")

print("✅ Colonnes 'Valeur' converties en numérique.")

✅ Colonnes 'Valeur' converties en numérique.

In [39]:
# Vérification des unités présentes dans le sous-ensemble volaille
volaille_selected[["Élément", "Unité"]].drop_duplicates().sort_values(by="Élément")

,Élément,Unité
659,Disponibilité alimentaire (Kcal/personne/jour),Kcal/personne/jour
658,Disponibilité alimentaire en quantité (kg/personne/an),kg
661,Disponibilité de matière grasse en quantité (g/personne/jour),g/personne/jour
660,Disponibilité de protéines en quantité (g/personne/jour),g/personne/jour
654,Disponibilité intérieure,Milliers de tonnes
1707,Exportations - Quantité,Milliers de tonnes
652,Importations - Quantité,Milliers de tonnes
651,Production,Milliers de tonnes

In [40]:
# Vérification des unités présentes dans la population
population_2017[["Élément", "Unité"]].drop_duplicates()

              Élément           Unité
17  Population totale  1000 personnes

In [41]:
# Vérification des années après filtrage
print("Années présentes dans volaille_selected :", volaille_selected["Année"].unique())
print("Années présentes dans population_2017 :", population_2017["Année"].unique())

Années présentes dans volaille_selected : [2017]
Années présentes dans population_2017 : [2017]

In [42]:
# Contrôle rapide de cohérence des valeurs numériques
print("Résumé statistique — volaille_selected")
display(volaille_selected["Valeur"].describe())

print("Résumé statistique — population_2017")
display(population_2017["Valeur"].describe())

Résumé statistique — volaille_selected

count     1331.000000
mean       217.998565
std       1227.993580
min          0.000000
25%          4.000000
50%         14.110000
75%         69.000000
max      21914.000000
Name: Valeur, dtype: float64

Résumé statistique — population_2017

count    2.360000e+02
mean     3.198362e+04
std      1.318949e+05
min      7.930000e-01
25%      3.803032e+02
50%      5.203511e+03
75%      1.930842e+04
max      1.421022e+06
Name: Valeur, dtype: float64

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">📏</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.3 — Contrôle des types et unités</b>
  </div>
  <p style="margin:0 0 12px 0;">
    Les types de données, les unités de mesure et le périmètre temporel ont été vérifiés afin de garantir
    la cohérence technique du jeu de données avant la fusion et la création de variables dérivées.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(280px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Contrôles validés</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Colonne <b>Valeur</b> convertie en numérique</li>
        <li>Année confirmée : <b>2017</b> dans les deux sous-ensembles</li>
        <li>Unités cohérentes par indicateur</li>
        <li>Population exprimée en <b>1000 personnes</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(250,204,21,0.08);
      border:1px solid rgba(250,204,21,0.28);
    ">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">📌 Unités relevées</div>
      <ul style="margin:0; padding-left:18px;">
        <li>Kcal/personne/jour</li>
        <li>kg/personne/an</li>
        <li>g/personne/jour</li>
        <li>Milliers de tonnes</li>
        <li>1000 personnes</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(34,197,94,0.08);
    border:1px solid rgba(34,197,94,0.28);
  ">
    ✅ <b style="color:#86EFAC;">Conclusion :</b><br>
    Les unités observées sont cohérentes avec les indicateurs sélectionnés. Le périmètre temporel est bien aligné sur 2017,
    ce qui rend la comparaison entre les sources possible.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    📌 <b style="color:#FDE68A;">Point important :</b><br>
    La cohérence des unités est essentielle avant toute fusion ou création de variables dérivées.
    À ce stade, rien n’indique d’erreur technique majeure sur les types ou les mesures.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.26);
  ">
    👉 <b style="color:#F9A8D4;">En clair :</b><br>
    Cette étape est validée. Les données sont techniquement exploitables pour construire un dataset pays,
    à condition de bien gérer ensuite les pays incomplets et les différences de couverture entre sources.
  </div>
</div>

<a id="etape3_4"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,186,116,0.28);
  border-radius:12px;
  background:rgba(253,186,116,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(85%) sepia(17%) saturate(1388%) hue-rotate(334deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>3.4 • Gestion des valeurs manquantes</span>
  </h3>
</div>

In [43]:
# Valeurs manquantes dans le sous-ensemble volaille_selected
missing_volaille = volaille_selected.isnull().sum().sort_values(ascending=False)
missing_volaille[missing_volaille > 0]

Series([], dtype: int64)

In [44]:
# Valeurs manquantes dans population_2017
missing_pop_2017 = population_2017.isnull().sum().sort_values(ascending=False)
missing_pop_2017[missing_pop_2017 > 0]

Note    235
dtype: int64

In [45]:
# Vérification du nombre d'indicateurs disponibles par pays
# Chaque pays devrait idéalement disposer des 8 indicateurs retenus
nb_indicateurs_par_pays = (
    volaille_selected.groupby("Zone")["Élément"]
    .nunique()
    .sort_values()
)

nb_indicateurs_par_pays.head(20)

Zone
Ouzbékistan                              4
République démocratique populaire lao    4
Maldives                                 6
Djibouti                                 6
Cambodge                                 7
Cabo Verde                               7
Bahamas                                  7
Afghanistan                              7
Guinée-Bissau                            7
Gambie                                   7
Guinée                                   7
Grenade                                  7
Haïti                                    7
Kiribati                                 7
Cuba                                     7
Bangladesh                               7
Madagascar                               7
Mauritanie                               7
Mozambique                               7
Malawi                                   7
Name: Élément, dtype: int64

In [46]:
# Pays avec moins de 8 indicateurs disponibles
pays_incomplets = nb_indicateurs_par_pays[nb_indicateurs_par_pays < len(elements_retenus)]
pays_incomplets

Zone
Ouzbékistan                              4
République démocratique populaire lao    4
Maldives                                 6
Djibouti                                 6
Cambodge                                 7
Cabo Verde                               7
Bahamas                                  7
Afghanistan                              7
Guinée-Bissau                            7
Gambie                                   7
Guinée                                   7
Grenade                                  7
Haïti                                    7
Kiribati                                 7
Cuba                                     7
Bangladesh                               7
Madagascar                               7
Mauritanie                               7
Mozambique                               7
Malawi                                   7
Nouvelle-Calédonie                       7
Népal                                    7
République centrafricaine                7
Mongolie                                 7
Mali                                     7
Timor-Leste                              7
Sao Tomé-et-Principe                     7
Soudan                                   7
République-Unie de Tanzanie              7
Saint-Vincent-et-les Grenadines          7
Sainte-Lucie                             7
Burkina Faso                             7
Tadjikistan                              7
Zimbabwe                                 7
Éthiopie                                 7
Turkménistan                             7
Vanuatu                                  7
Name: Élément, dtype: int64

In [47]:
# Vérification de la disponibilité de la population 2017 par pays
population_2017["Zone"].nunique(), population_2017.shape

(236, (236, 15))

In [48]:
# Première liste de pays potentiellement fragiles
# (à surveiller)
print("Nombre de pays avec moins de 8 indicateurs :", pays_incomplets.shape[0])

Nombre de pays avec moins de 8 indicateurs : 37

In [49]:
# On garde pour l'instant le maximum d'information
# mais on crée une liste de pays complets pour la suite
pays_complets = nb_indicateurs_par_pays[
    nb_indicateurs_par_pays == len(elements_retenus)
].index.tolist()

print("Nombre de pays complets sur les 8 indicateurs :", len(pays_complets))

Nombre de pays complets sur les 8 indicateurs : 135

<div style="
  font-family:Segoe UI, Arial, sans-serif;
  font-size:16px;
  color:#f4f4f5;
  background:linear-gradient(135deg, rgba(88,42,7,0.96), rgba(18,18,24,0.98));
  padding:18px 22px;
  border-radius:14px;
  border:1px solid rgba(251,146,60,0.35);
  width:min(980px, 95%);
  margin:22px auto;
  box-shadow:0 0 22px rgba(0,0,0,0.45);
  line-height:1.6;
">
  <div style="display:flex; align-items:center; gap:10px; margin-bottom:12px;">
    <span style="font-size:20px;">🧩</span>
    <b style="font-size:19px; color:#FDBA74;">Étape 3.4 — Gestion des valeurs manquantes</b>
  </div>

  <p style="margin:0 0 12px 0;">
    Les valeurs manquantes ont été contrôlées afin d’identifier les pays incomplets et d’anticiper les futurs filtres qualité.
    L’objectif n’est pas encore d’exclure massivement des pays, mais de repérer les cas fragiles.
  </p>
  <div style="
    display:grid;
    grid-template-columns:repeat(auto-fit, minmax(280px, 1fr));
    gap:12px;
    margin:14px 0;
  ">
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(34,197,94,0.08);
      border:1px solid rgba(34,197,94,0.28);
    ">
      <div style="font-weight:700; color:#86EFAC; margin-bottom:6px;">✅ Points rassurants</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>0</b> valeur manquante utile dans <b>volaille_selected</b></li>
        <li>La colonne <b>Note</b> de la population contient des NA, mais elle n’est pas utilisée</li>
        <li><b>135 pays</b> disposent bien des <b>8 indicateurs</b></li>
      </ul>
    </div>
    <div style="
      padding:12px 2px;
      border-radius:12px;
      background:rgba(250,204,21,0.08);
      border:1px solid rgba(250,204,21,0.28);
    ">
      <div style="font-weight:700; color:#FDE68A; margin-bottom:6px;">⚠️ Points à surveiller</div>
      <ul style="margin:0; padding-left:18px;">
        <li><b>37 pays</b> ont moins de 8 indicateurs disponibles</li>
        <li>Certains pays n’ont que <b>4, 6 ou 7 indicateurs</b></li>
        <li>Ces pays devront être réévalués après la fusion</li>
      </ul>
    </div>
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(236,72,153,0.08);
    border:1px solid rgba(236,72,153,0.28);
  ">
    📌 <b style="color:#F9A8D4;">Lecture métier :</b><br>
    Les données sur la volaille sont globalement propres, ce qui est un très bon signal. Le principal enjeu ne vient pas
    de valeurs manquantes brutes, mais plutôt de la <b>complétude inégale selon les pays</b>.
  </div>
  <div style="
    margin-top:12px;
    padding:12px 6px;
    border-radius:12px;
    background:rgba(250,204,21,0.08);
    border:1px solid rgba(250,204,21,0.28);
  ">
    ⚠️ <b style="color:#FDE68A;">Décision à ce stade :</b><br>
    Il n’est pas nécessaire de supprimer immédiatement ces 37 pays. En revanche, ils doivent être marqués comme
    <b>pays incomplets à surveiller</b> lors de la construction du dataset final.
  </div>
</div>

<a id="etape4"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(52,211,153,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(6,74,53,0.96), rgba(5,37,27,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(78%) sepia(32%) saturate(1109%) hue-rotate(113deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span style="color:#FFFFFF;">🔗 Étape 4</span>
    <span>• Construction du dataset d’analyse</span>
  </h2>
</div>

<a id="etape4_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(134,239,172,0.28);
  border-radius:12px;
  background:rgba(134,239,172,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(89%) sepia(17%) saturate(874%) hue-rotate(88deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span>4.1 • Pivot des données par pays</span>
  </h3>
</div>

<a id="etape4_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(134,239,172,0.28);
  border-radius:12px;
  background:rgba(134,239,172,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(89%) sepia(17%) saturate(874%) hue-rotate(88deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span>4.2 • Intégration de la population</span>
  </h3>
</div>

<a id="etape4_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(134,239,172,0.28);
  border-radius:12px;
  background:rgba(134,239,172,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(89%) sepia(17%) saturate(874%) hue-rotate(88deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span>4.3 • Ajout d’éventuelles sources externes</span>
  </h3>
</div>

<a id="etape4_4"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(134,239,172,0.28);
  border-radius:12px;
  background:rgba(134,239,172,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(89%) sepia(17%) saturate(874%) hue-rotate(88deg) brightness(101%) contrast(101%);
      ">
    </a>
    <span>4.4 • Vérification du périmètre final (100 pays minimum)</span>
  </h3>
</div>

<a id="etape5"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(244,114,182,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(92,8,54,0.96), rgba(48,7,29,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(79%) sepia(23%) saturate(1712%) hue-rotate(291deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span style="color:#FFFFFF;">🛠️ Étape 5</span>
    <span>• Feature engineering</span>
  </h2>
</div>

<a id="etape5_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(249,168,212,0.28);
  border-radius:12px;
  background:rgba(249,168,212,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(18%) saturate(832%) hue-rotate(281deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>5.1 • Création des variables dérivées</span>
  </h3>
</div>

<a id="etape5_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(249,168,212,0.28);
  border-radius:12px;
  background:rgba(249,168,212,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(18%) saturate(832%) hue-rotate(281deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>5.2 • Contrôle de cohérence des nouvelles variables</span>
  </h3>
</div>

<a id="etape5_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(249,168,212,0.28);
  border-radius:12px;
  background:rgba(249,168,212,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(88%) sepia(18%) saturate(832%) hue-rotate(281deg) brightness(103%) contrast(102%);
      ">
    </a>
    <span>5.3 • Dataset final prêt pour l’ACP</span>
  </h3>
</div>

<a id="etape6"></a>
<div style="
  width:78%;
  margin:16px auto 10px auto;
  border:1px solid rgba(250,204,21,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(88,64,5,0.96), rgba(44,31,4,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(84%) sepia(49%) saturate(1328%) hue-rotate(346deg) brightness(103%) contrast(101%);
      ">
    </a>
    <span style="color:#FFFFFF;">🔎 Étape 6</span>
    <span>• Analyse exploratoire des données</span>
  </h2>
</div>

<a id="etape6_1"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,230,138,0.28);
  border-radius:12px;
  background:rgba(253,230,138,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(92%) sepia(19%) saturate(938%) hue-rotate(335deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>6.1 • Statistiques descriptives</span>
  </h3>
</div>

<a id="etape6_2"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,230,138,0.28);
  border-radius:12px;
  background:rgba(253,230,138,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(92%) sepia(19%) saturate(938%) hue-rotate(335deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>6.2 • Distribution des variables</span>
  </h3>
</div>

<a id="etape6_3"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,230,138,0.28);
  border-radius:12px;
  background:rgba(253,230,138,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(92%) sepia(19%) saturate(938%) hue-rotate(335deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>6.3 • Détection des outliers</span>
  </h3>
</div>

<a id="etape6_4"></a>
<div style="
  width:78%;
  margin:8px auto 10px auto;
  border:1px solid rgba(253,230,138,0.28);
  border-radius:12px;
  background:rgba(253,230,138,0.05);
  box-sizing:border-box;
">
  <h3 style="
    margin:0;
    padding:12px 18px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:18px;
    font-weight:700;
    gap:10px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:22px; height:22px; display:block;
        filter: brightness(0) saturate(100%) invert(92%) sepia(19%) saturate(938%) hue-rotate(335deg) brightness(102%) contrast(101%);
      ">
    </a>
    <span>6.4 • Première lecture business des profils pays</span>
  </h3>
</div>

<a id="conclusion1"></a>
<div style="
  width:78%;
  margin:18px auto 14px auto;
  border:1px solid rgba(34,211,238,0.34);
  border-radius:14px;
  background:linear-gradient(135deg, rgba(5,72,86,0.96), rgba(4,34,42,0.98));
  box-sizing:border-box;
">
  <h2 style="
    margin:0;
    padding:15px 20px;
    color:#FFFFFF;
    display:flex;
    align-items:center;
    font-family:'Segoe UI', Arial, sans-serif;
    font-size:22px;
    font-weight:750;
    gap:12px;
  ">
    <a href="#top" style="display:flex; align-items:center; justify-content:center; text-decoration:none; flex-shrink:0;">
      <img src="assets/img/house-solid-full.svg" alt="Sommaire" style="
        width:24px; height:24px; display:block;
        filter: brightness(0) saturate(100%) invert(82%) sepia(22%) saturate(1433%) hue-rotate(148deg) brightness(104%) contrast(102%);
      ">
    </a>
    <span style="color:#FFFFFF;">✅ Conclusion</span>
    <span>• Synthèse du notebook 1</span>
  </h2>
</div>